= Building Red Hat Device Edge Images
:navtitle: Home

== Objective

This course teaches how to create *Red Hat Device Edge* images for edge devices and kiosk computers using Red Hat Enterprise Linux (RHEL), more specifically its *RHEL for Edge* features. It focus on:

* Using the Image Builder tool to create and deploy edge images based on the RPM-OSTree technology.
* Performing OSTree repository management to deliver updates to edge devices.

It is part of a Red Hat Device Learning path, which currently includes three courses in two different tracks:

* For customers using RHEL for Edge and RPM-OSTree based edge images:
** *Building Red Hat Device Edge Images* (this course)
** https://redhatquickcourses.github.io/rhde-microshift/[Deploying MicroShift on Red Hat Device] (follow-up course)

* For customers using RHEL image mode:
** https://redhatquickcourses.github.io/rhde-microshift-bootc/[Deploying MicroShift on RHEL Image Mode]

IMPORTANT: Red Hat employees must enroll using its https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D66848400[LMS entry] to get completion credits, and Red Hat Partners must enroll using its https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D66848513[Partner Portal entry].


== Audience

Operations-focused roles, who design and implement device edge images, but are not usually in-person at edge sites, such as:

* System Administrations (IT - Information Technology, and OT - Operations Technology)
* Site Reliability Engineers (SREs)
* DevOps Engineers

Red Hat and Partner roles that perform demonstrations, PoC and PoV of Red Hat Device Edge as part of sales engagement, such as Solutions Architects.

Red Hat and Partner roles that support Red Hat Device Edge on customers, such as Services Consultants and Customer Support Engineers.

== Prerequisites

* Familiarity with RHEL system administration, to the level of RHCA (Red Hat Certified System Administrator) or equivalent knowledge

* Familiarity with Ansible playbooks and Ansible Automation Platform is useful but not required.

* Familiarity with web server administration, such as Apache Web Server or NGinx, is useful but not required.

* Familiarity with KVM virtual machine management using Libvirt, is useful but not required.

== Classroom Environment

You can perform all activities in this course using the virtual classroom lab from *HOL014: Red Hat Device Edge Quick Course Series*, which is shared by all Red Hat Device Edge quick courses and will be updated as required by future related courses.

Use the following links to access the virtual classroom lab on Red Hat Online Learning (ROLE):

* https://role.rhu.redhat.com/rol-rhu/app/courses/hol014-9.5/pages/pr01[HOL014 for Red Hat employees^].
* https://rol.redhat.com/rol/app/courses/hol014-9.5/pages/pr01[HOL014 for Red Hat partners and customers^] with a *Red Hat Learning Subscription*.

After you enter HOL014 on ROLE, follow the instructions there to create a new course classroom lab and access its virtual machines. If you already created a HOL014 classroom for another Red Hat Device Edge quick course, you can continue using the same classroom lab.

Beware that ROLE classrooms have timers after which classroom labs are stopped and deleted, to conserve compute resources. If you plan to use the same classroom lab for multiple Red Hat Device Edge quick courses, do not wait too long to continue. You do not need to use the same classroom for multiple courses: each course provides step-by-step instructions to start from either a new classroom lab or to continue from an existing classroom lab.

You will follow this quick course by alternating between two browser windows: one to navigate quick course materials, such as this page; and another to access the virtual classroom lab, to perform hands-on activities.

If you can provision your own RHEL servers or VMs, it should be possible to configure all that is required for the hands-on activities by using a https://developers.redhat.com/products/rhel/download[free subscription] from the https://developers.redhat.com/about[Red Hat Developer Program], which gives access to RHEL installation media, RHEL package repositories, OpenShift package repositories, and OpenShift container images in Red Hat registries.

== About Red Hat Online Learning (ROLE) and Red Hat Learning Subscription

The Red Hat Online Learning (ROLE) web site provides https://www.redhat.com/en/services/training-and-certification[Red Hat Training and Certification] course materials and their virtual classrooms labs. You must be enrolled in a Red Hat Training course or subscription to have access to ROLE.

NOTE: The Red Hat Device Edge Quick Courses Series use ROLE for its virtual classroom labs only, and hosts courses materials outside of ROLE, as GitHub pages.

A basic https://www.redhat.com/en/services/training/learning-subscription[Red Hat Learning Subscription] offers access to a number Red Hat Training courses and virtual classroom lab time. Higher subscription tiers offer additional benefits such as Red Hat Certification Exam vouchers.

== Course Updates

This course was updated to use classroom labs based on RHEL 9.5 and to share the same classroom labs (HOL014) with other Red Hat Device Edge courses. If you started this course using the previous RHELL 9.2 classroom labs (HOL014) we suggest that you start over using a new classroom environment.

== Other Sources of Information About Red Hat Device Edge

The main product documentation of Red Hat Device Edge is an https://docs.redhat.com/en/documentation/red_hat_device_edge/4/html/overview/index[overview document], which points to the product documentation of RHEL, OpenShift, and Ansible.

For the scope of this course, the main product documentation of RHEL for Edge is https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/composing_installing_and_managing_rhel_for_edge_images/index[Composing, installing, and managing RHEL for Edge images].

More extensive documentation about RHEL Image Builder is on https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/composing_a_customized_rhel_system_image/index[Composing a customized RHEL system image].

We also recommend the community upstream documentation of the technologies in RHEL for Edge that we use in the activities of this course:

* https://osbuild.org/docs/user-guide/introduction/[Image Builder (osbuild)].
* https://coreos.github.io/rpm-ostree/[RPM-OSTree]
* https://ostreedev.github.io/ostree/[OSTree (libostree)].

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

Special thanks to *Micah Abbott* for all his support while writing this course and testing its hands-on activities.

Many thanks to Daniel Froehlich, Eric Lavarde, Jeff Ligon, Lester Claudio, Luis Arizmendi, Mourad Nakib, Sayan Paul, and Shauna Diaz for their support reviewing the course design, its outline, work-in-progress contents, and answering my newbie questions.
