= Building Red Hat Device Edge Images
:navtitle: Home

== Objective

This course teaches how to create *Red Hat Device Edge* images for edge devices and kiosk computers using Red Hat Enterprise Linux (RHEL), more specifically its *RHEL for Edge* features. It focus on:

* Using the Image Builder tool to create and deploy edge images based on the RPM-OSTree technology.
* Performing OSTree repository management to deliver updates to edge devices.

== Audience

Operations-focused customer roles, who design and implement device edge images, but are not usually in-person at edge sites, such as:

* System Administrations (IT - Information Technology, and OT - Operations Technology)
* Site Reliability Engineers (SREs)
* DevOps Engineers

Red Hat and Partner roles that perform demonstrations, PoC and PoV of Red Hat Device Edge as part of sales engagement, such as Solutions Architects.

Red Hat and Partner roles that support Red Hat Device Edge on customers, such as Services Consultants and Customer Support Engineers.

== Prerequisites

* Familiarity with RHEL system administration, to the level of RHCA (Red Hat Certified System Administrator) or equivalent knowledge

* Familiarity with Ansible playbooks and Ansible Automation Platform is useful but not required.

* Familiarity with web server administration, such as Apache Web Server or NGinx, is useful but not required.

* Familiarity with KVM virtual machine management using Libvirt, is useful but not required.

== Classroom Environment

You can perform all activities in this course using the virtual classroom from https://role.rhu.redhat.com/rol-rhu/app/courses/hol007-9.2/pages/pr01[HOL007: Red Hat Enterprise Linux (RHEL): Create the RHEL for Edge Image], based on RHEL 9.2.

A new classroom in is the works, featuring a newer RHEL release, and which will be shared by future Red Hat Device Edge courses. This page will be updated with links and details about the new classroom, when it is available.

== Other Sources of Information About Red Hat Device Edge

The main product documentation of Red Hat Device Edge is an https://docs.redhat.com/en/documentation/red_hat_device_edge/4/html/overview/index[overview document], which points to the product documentation of RHEL, OpenShift, and Ansible.

For the scope of this course, the main product documentation of RHEL for Edge is https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/composing_installing_and_managing_rhel_for_edge_images/index[Composing, installing, and managing RHEL for Edge images].

More extensive documentation about RHEL Image Builder is on https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/composing_a_customized_rhel_system_image/index[Composing a customized RHEL system image].

We also recommend the community upstream documentation of the technologies in RHEL for Edge that we use in the activities of this course:

* https://osbuild.org/docs/user-guide/introduction/[Image Builder (osbuild)].
* https://coreos.github.io/rpm-ostree/[RPM-OSTree]
* https://ostreedev.github.io/ostree/[OSTree (libostree)].

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

Special thanks to *Micah Abbott* for all his support while writing this course and testing its hands-on activities.

Many thanks to Daniel Froehlich, Eric Lavarde, Jeff Ligon, Lester Claudio, Luis Arizmendi, Mourad Nakib, Sayan Paul, and Shauna Diaz for their support reviewing the course design, its outline, work-in-progress contents, and answering my newbie questions.