:time_estimate: 5

= Introduction to OSTree Technology

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Understand how OSTree repositories represent operating system images

WARNING: Work In Progress


== Edge Images and RPM-OSTree

Edge images from Image Builder are based on the OSTree technology, which configures the root filesystem as read-only. Well, not the true root file system, it's actually a chroot, but you learn those details later in this course. In an OSTree-based system, you cannot change a system file, not even as root, except by deploying a new system image an rebooting into the new image.

OSTree can keep multiple system images side-by-side in a system, so downloading updates does not affect a running system -- constrast that with RPM package updates, which can alter files which are in use by running processes and produce unpredictable results.

You can reboot an OSTree system into any of the available system images, making it trivial to rollback a system update to a previous known good image -- constrast that with rolling back an update of multiple RPM packages. With package-based systems, you can select an older kernel at boot, but you cannot easily revert all system binaries which depend on the kernel version.

OSTree allows writes to only `/etc` and `/var`, which are treated in different ways:

*  Files in `/var` are only touched at first boot, when they're copied from the system image to the writable file system, but updates keep the contents in `/var` as they are.

* Files in `/etc` are updated with a three-way merge process: the current `/etc` contents are compared with the original system image, differences are applied to the contents of `/etc` from the new system image, and the result saved to the writable file system.

The goal is, on one side, to preserve application data in `/var` across system updates, and on the other side, enable new system images to bring new configuration files and change configuration defaults, while preserving local customizations applied to the running system.

[ figure of read-only /usr and read-write /etc and /var. Also /sysroot? ]

The OSTree technology is not designed to be usable by itself, but to be infrastructure under higher-level Linux distribution tooling. In RHEL, the higher level infrastructure is RPM-OSTree, which builds OSTree system images from RPM packages.

RPM-OSTree also enables installing RPM packages in an image-based by creating a file system layer of local customizations, which you can either keep or discard during system updates. It is not expected that edge systems abuse that feature of RPM-OSTreem but it can be handy during development and troubleshooting of edge images.

Image Builder users do not interact with the RPM-OSTree and OSTree tooling directly, at least not to build edge images. But they must interact with RPM-OSTree to distribute and apply updates to edge systems.

== Publishng OSTree Commits

OSTree is, conceptually, very similar to Git: both are designed to manage changes to file trees as atomic units, providing transactional updates and rollbacks to those trees. Both are also designed to manage multiple concurrent branches and to be efficient on both disk space and network bandwidth when handling deltas between two versions (or two commits) of the same file tree.

Why not just using Git? OSTree adds the following features, which are required to manage bootable Linux file systems but are not needed to manage application source code:

* Recording SELinux labels and POSIX extended attributes
* Installing booloaders, Linux Kernels, and initial ramdisks

Similar to Git, a client OSTree system contains a copy (or a clone) of a remote OSTree repository, and it can pull changes from the remote repository. Unlike Git, OSTree is optimized for handling large binary files, as opposed to small text files.

Another practical difference between OSTree and Git is the fact that OSTree provides no specialized server software: OSTree repositories are just files serverd by a standard HTTP server. You manage OSTree repositories using local file system access, and remote access over HTTP works only for downloading (pulling) updates from a remote to a local repository.

While this means that managing remote OSTree repositories requires more effort than with Git, it also means you don't need to learn how to deploy and manage special server software: you just need to learn how to use the client-side OSTree tools. Actually you only need to learn the client tools from the higher-level abstraction above OSTree, which is RPM-OSTree in the case of RHEL for Edge,.

== OSTree Static Deltas

[ Move this heading to the update topic? ]

Unlike Git, OSTree is designed to be able to easily and cleanly discard history, on the assumption that all operating system binaries in a commit can be recreated from their source code. An OSTree repository is not intended for long-term change tracking and auditing: these are best done on the source code rather than on the derived binaries.

OSTree repositories can include OSTree commits with no change history between them, and are nonetheless able to deduplicate file contents between commits on both on local and remote repositories. OSTree also optimizes network traffic by sending only deltas between repositories. So you can build many OSTree commits in a development system, using its local repository, and only promote for production usage, in a remote repository, a few commits which passed unit tests and functional tests.

But, as Git users know, computing deltas and transfering them on-demand, one file at a time, is not the most efficient method. I requires multiple network transactions and incurrs in lots of protocol overhead. OSTree offers the possibility of precomputing and storing static deltas between two commits as part of an OSTree repository.

OSTree clients will discover and use these precomputed deltas, called *static deltas*, transparently, saving network bandwidth and reducing the time to download updates. The savings are even more noticeable in high-latency networks.

[ figure of multiple commits and deltas, and clients downloading either a commit or a delta ]

Having static deltas also reduces the memory and CPU requirements of both clients and servers when updating systems. If you consider that an OSTree server has a potentially large population of client edge devices, compared to the population of developers using a Git repository, the efficiency gains can be large, not to mention a lower cloud bill for running your OSTree servers.

Precomputed static deltas also saves CPU from smaller edge devices while downloading and deploy system updates. The gains are wellcome by edge devices, which have slower CPUs and less memory than data center servers. This is also significant because edge devices are expected to contine performing their regular tasks while downloading (or staging) system updates.

== The RPM-OSTree tooling

The `rpm-ostree` command fetches and deploys system image updates from a remote OSTree repository, including performing any bootloader and kernel changes required by the new image.

A system image is downloaded and staged without affecting the running system. The new system image is only effective after a reboot.

RPM-OSTree keeps the previous system image unchanged on disk and can rollback to it, which also requires a reboot.

You can query the RPM database on the current system image, but you cannot install and update packages using `yum` and `dnf` commands. You must use the `rpm-ostree` command to first enable an overlay layer to record changes to the system, and them install new packages or update packages from the current system images.

It is possible ot update the system image and keep the overlay, as long as the overlay does not include packages with releases olde than the new system image.

In this course, we will not teach the use of overlays and managing packages on RHEL for Edge. We focus on building and updating system images.

== The OSTree tooling

Lorem Ipsum

[ Either add an introduction to the syntax of the rpm-ostree command, or move this heading to another topic ]

[ Do we need to introduce the ostree command? For example, can I check the integrity of an ostree commit (or edte commit image) from rpm-ostree aline? ]

== Next Steps

Now that you was introduced to the essential concepts of RPM-OSTree, a series of hands-on activties install and configure a web server to host remote OSTree repositories and publish simple edge images on that web server. Later in this course you will test those edge images using local VMs, and them update those VMs to use new system images.
