:time_estimate: 5

= Lab: Publish Edge Images on Remote OSTree Repositories

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Publish an Image Builder edge commit image in a remote HTTP server so it is available to edge devices.

WARNING: Work In Progress

== Before you Begin

You need a develoment machine with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your test machine was configured and verified by following the instructions from the xref:s4-install-lab.adoc[first lab].

You need a second machine to run a web server, to which you have unrestricted sudo access to install packages and configure system services.

You could run the web server in the same machine you use to run the Image Builder service, and that would match some CI/CD environments, but production environments usually require a dedicated and hardened server acessible to remote edge devices in multiple locations. 

You also need the edge commit image that was created and downloaded to your user home directory by the xref:s6-compose-lab.adoc[previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. If not, please adapt the instructions to your test environment.

== Instructions

[ switch everyhere to use the hostname in the prompt? ]

[ have the user created on the blueprint instead of by kickstart? use a name other than "core", and mention SSH keys ]

1. On your development machine, verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Verify that you have a tar file named `_uuid_-compose.tar` that contains the edge commit image from the xref:s6-compose-lab.adoc[previous lab]. Its file name will be different from the following output because Image Builder generates new UUIDs for every compose.
+
[source,subs="verbatim,quotes"]
--
$ *ls *commit.tar*
_575d8ddc-2902-4de3-a0d5-82f5f194f5d8_-commit.tar
--

.. To ease the following steps, copy and paste the UUID from the file name to a shell variable.
+
[source,subs="verbatim,quotes"]
--
$ *UUID=_575d8ddc-2902-4de3-a0d5-82f5f194f5d8_*
--

.. If you deleted the temporary directory from the previous lab, extract the image contents again to a temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf $UUID-commit.tar -C delete-me*
--


2. Check the integrity of your edge commit image by inspecting its OSTree repository.

.. Get the commit ID from the compose metadata and store it in a shell variable. You will get a different ID than the one shown here.
+
[source,subs="verbatim,quotes"]
--
$ *COMMIT=$(jq -r '.["ostree-commit"]' < delete-me/compose.json)*
$ *echo $COMMIT*
4afeda6a96ec8b2c263b6965a9c3f92db1db2436ae1e1233da70b7776fc6137b
--
+
You would not need the commit ID for an OSTree repository with a single commit, as the one you got from your only edge commit image, but as you build more edge images, or update existing images, you will need to differentiate between multiple commits in the same OSTree repository.

.. Get the branch reference from the compose metadata and store it in a shell variable.
+
[source,subs="verbatim,quotes"]
--
$ *REF=$(jq -r '.["ref"]' < delete-me/compose.json)*
$ *echo $REF*
rhel/9/x86_64/edge
--
+
You would not need the branch reference for an OSTree repository with a single commit, as the one you got from your only edge commit image, but as you build more edge images, you will need to assign each a different branch name, so you can publish all of them on the same OSTree repository.

.. List the commits available on your OSTree repository. There should be only one commit which matches the compose metadata.
+
[source,subs="verbatim,quotes"]
--
$ *ostree --repo=delete-me/repo log $REF*
commit 4afeda6a96ec8b2c263b6965a9c3f92db1db2436ae1e1233da70b7776fc6137b
ContentChecksum:  549eb067bbcfa59a90f1948e75702a34a857122a74d9936c062bc64349f24330
Date:  2024-09-06 22:07:45 +0000
Version: 9.2
(no subject)
--

.. List the branches available on your OSTree repository. There should be only one branch which matches the compose metadata.
+
[source,subs="verbatim,quotes"]
--
$ *ostree --repo=delete-me/repo refs*
rhel/9/x86_64/edge
--

.. Peform an integrity check of the OSTree repository.
+
[source,subs="verbatim,quotes"]
--
$ *ostree --repo=delete-me/repo fsck*
Validating refs...
Validating refs in collections...
Enumerating commits...
Verifying content integrity of 1 commit objects...
fsck objects (28670/28670) [=============] 100%
object fsck of 1 commits completed successfully - no errors found.
--


3. On your web server machine, configure a web server dedicated to providing OSTree repositories.
+
The instructions bellow confingure an Apache Web Server as a system service on the `servera` machine. You could use the NGinx web server and run the web server as a container, among other variations.
+
WARNING: Production deployments usually require further customization, such as enabling TLS connections, using trusted certificates, and requiring authentication, which are not performed here.

.. On another terminal, start an SSH session on your web server machine (`servera`), and copy the shell variable from the first terminal.
+
[source,subs="verbatim,quotes"]
--
$ *ssh servera*
$ *UUID=_575d8ddc-2902-4de3-a0d5-82f5f194f5d8_*
--

.. Install the Apache Web Server packages from RHEL.
+
[source,subs="verbatim,quotes"]
--
$ *sudo yum install -y httpd*
...
Complete!
--

.. Enable and start the Apache Web Server system service.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl enable httpd*
Created symlink /etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service.
$ *sudo systemctl start httpd*
...
--

.. Enable remote access to the Apache Web Server on the system's firewall.
+
[source,subs="verbatim,quotes"]
--
$ *sudo firewall-cmd --add-service=http --permanent*
success
$ *sudo firewall-cmd --reload*
success
--

.. Install the RPM-OSTree and the lower level OSTree tooling on the web server machine, just in case you need to perform maintenance on the OSTree repositories you will store on it.
+
[source,subs="verbatim,quotes"]
--
$ *sudo yum install -y rpm-ostree ostree*
...
Complete!
--

4. On your development machine, check that you have access to the web server machine and copy the edge commit image, generated in the xref:s6-compose-lab.adoc[previous lab], to the web server.

.. Use a web browser or any web client to access the default welcome page from the Apache Web Server.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com*
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
        <head>
                <title>Test Page for the HTTP Server on Red Hat Enterprise Linux</title>
...
--

.. Copy the edge commit image to your home directory on the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *scp $UUID-commit.tar servera.lab.example.com:~*
...
--

5. Still on your development manchine, create an Anacond Kickstart file that points to the OSTree repository on the web server.

.. Using your preferred text editor, create a file named `rhel9-httpd.ks` with the following contents:
+
[source,subs="verbatim,quotes"]
--
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text

zerombr
clearpart --all --initlabel
autopart --type=plain
rootpw --lock
user --name=core --group=wheel --password=redhat123

reboot

network --bootproto=dhcp 
ostreesetup --nogpg --osname=rhel --remote=edge --url=http://servera.lab.example.com/repo/ --ref=rhel/9/x86_64/edge
--
+
You can also downlod the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/ks/rhel9-httpd.ks[kickstart file] from sample applications repository in GitHub.
+
Most lines on that kickstart file can be changed according to needs, and real-world deployments would include items such as SSH keys for remote login and remote management. The important piece is the `ostreesetup` command, which directs Anaconda to download the latest commit from a remote OSTree repository using HTTP.

.. Copy the Kickstart file to your home directory on the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *scp rhel9-httpd.ks servera.lab.example.com:~*
...
--

6. Switch to your web sever machine and publish the kickstart file and the OSTree commit in the web server content directory.

.. Copy the kickstart file to the web server content directory.
+
[source,subs="verbatim,quotes"]
--
$ *ls -1*
_575d8ddc-2902-4de3-a0d5-82f5f194f5d8_-commit.tar
rhel9-httpd.ks
$ *sudo cp rhel9-httpd.ks /var/ww/html*
--

.. Extract the OSTree commit to the web server content directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo tar xf ~/$UUID-commit.tar -C /var/www/html*
--
+
IMPORTANT: Extracting an edge commit image only works for initializing a new OSTree repository with a single branch and commit. If you must add multiple edge images to the same OSTree repository, or you need to add updates to an edge image, you must use the `ostree pull-local` command. This command will be presented in a later chapter of this course, when we teach how to publish and apply updates.

.. Ensure the OSTree repository contents are acessible to the `apache` user and have correct SELinux labels.
+
[source,subs="verbatim,quotes"]
--
$ *ls -lZ /var/www/html*
total 5
-rw-r--r--. 1 root root unconfined_u:object_r:httpd_sys_content_t:s0 553 Sep  6 18:07 compose.json
drwxr-xr-x. 7 root root unconfined_u:object_r:httpd_sys_content_t:s0 102 Sep  6 18:07 repo
-rw-r--r--. 1 root root unconfined_u:object_r:httpd_sys_content_t:s0 317 Sep  6 18:07 rhel9-httpd.ks
--

.. If you need, change file permissions and SELinux labels.
+
[source,subs="verbatim,quotes"]
--
$ *sudo chmod -R a+X /var/www/html*
$ *sudo restorecon -R /var/www/html*
--

.. Remove the compose metadata, because you do not need it to serve OSTree content.
+
[source,subs="verbatim,quotes"]
--
$ *sudo rm compose.json*
--

7. Back to your development machine, verify that a remote client can access the kickstart file and the remote OSTree repository.

.. Check that a remote client can read the kickstart file over HTTP.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/rhel9-httpd.ks*
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --isUtc
...
--

.. Check that a remote client can read the OSTree repository configuration file. This way, you don't need to setup a local OSTree repository just to check access to the remode repository.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/config*
[core]
repo_version=1
mode=archive-z2
--

8. If you wish, you can now close the SSH connection to the web server machine and its terminal.

Now you have a web server configured to serve an OSTree repository and you have an edge system image stored on that OSTree repository.

//TODO create a second edge commit image, and publish it to a different branch of the same repo, to demonstrate ostree pull-local

== Next Steps

Before proceeding to test the edge image using a virtual machine, the next activity demonstates using Red Hat Ansible Automation Platform to automate building and publishing edge images.

