:time_estimate: 8

= Lab: Create a Remote OSTree Repository

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Publish an edge commit image from Image Builder in a remote HTTP server so it is available to edge devices.

WARNING: Pending SME Review & Proofreading

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your test machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a second machine, the _web server machine_, to run a web server, on which you have unrestricted sudo access to install packages and configure system services.

NOTE: You could run the web server in the same machine you use to run the Image Builder service, and that would match some CI/CD environments, but production environments usually require a dedicated and hardened server accessible to remote edge devices in multiple locations. 

You also need the edge commit image that was created and downloaded to your user home directory by the xref:ch1-build:s8-compose-lab.adoc[previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you will start SSH sessions to the `servera` VM from the same user. If not, please adapt the instructions to your test environment.

You will perform some steps of this lab on your _development machine_ and some steps on your _web server machine_. Pay attention to the instructions at each step!

== Instructions

// Switch everywhere to use the hostname in the prompt?

1. On your _development machine_, verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Verify that you have a tar file named `_uuid_-compose.tar` that contains the edge commit image from the xref:ch1-build:s8-compose-lab.adoc[previous lab]. Its file name will be different from the following output because Image Builder generates new UUIDs for every compose.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ls *commit.tar*
_{compose-uuid-httpd-v1-aaaaaaaaaaaa}_-commit.tar
--

.. To ease the following steps, copy and paste the UUID from the file name to a shell variable.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=_{compose-uuid-httpd-v1-aaaaaaaaaaaa}_*
--

.. If you deleted the temporary directory from the previous lab, extract the edge commit image contents again to a temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf $UUID-commit.tar -C delete-me*
--


2. Still on your _development machine_, check the integrity of your edge commit image by inspecting its OSTree repository.

.. Get the commit ID and branch name from the compose metadata and store them in shell variables. You will get a different ID than the one shown here.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *COMMIT=$(jq -r '.["ostree-commit"]' < delete-me/compose.json)*
$ *echo $COMMIT*
{commit-httpd-v1}
$ *REF=$(jq -r '.["ref"]' < delete-me/compose.json)*
$ *echo $REF*
rhel/9/x86_64/edge
--
+
NOTE: You would not need the commit ID nor branch name for an OSTree repository with a single commit, as the one you got from your first and only edge commit image. But as you build more edge images, or update existing images, you will need to be able to differentiate between multiple edge images, that is, multiple OSTree commits, in the same OSTree repository.

.. List the commits available on your OSTree repository. There should be only one commit which matches the compose metadata.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree --repo=delete-me/repo log $REF*
commit {commit-httpd-v1}
ContentChecksum:  549eb067bbcfa59a90f1948e75702a34a857122a74d9936c062bc64349f24330
Date:  2024-09-06 22:07:45 +0000
Version: 9.2
(no subject)
--

.. List the branches available on your OSTree repository. There should be only one branch which matches the compose metadata.
+
[source,subs="verbatim,quotes"]
--
$ *ostree --repo=delete-me/repo refs*
rhel/9/x86_64/edge
--

.. Peform an integrity check of the OSTree repository.
+
[source,subs="verbatim,quotes"]
--
$ *ostree --repo=delete-me/repo fsck*
Validating refs...
Validating refs in collections...
Enumerating commits...
Verifying content integrity of 1 commit objects...
fsck objects (28670/28670) [=============] 100%
object fsck of 1 commits completed successfully - no errors found.
--

3. Switch to your _web server machine_ and configure a web server dedicated to providing OSTree repositories.
+
The instructions bellow configure an Apache Web Server as a system service on the _web server machine_. You could use the NGinx web server and run the web server as a container, among other variations.
+
WARNING: Production deployments usually require further customization, such as enabling TLS connections, using trusted certificates, and requiring authentication, which are not performed here.

.. Open another terminal, log in on your _web server machine_, and copy the shell variable from the first terminal.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=_{compose-uuid-httpd-v1-aaaaaaaaaaaa}_*
--

.. Install the Apache Web Server packages from RHEL.
+
[source,subs="verbatim,quotes"]
--
$ *sudo yum install -y httpd*
...
Complete!
--

.. Enable and start the Apache Web Server system service.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl enable httpd*
Created symlink /etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service.
$ *sudo systemctl start httpd*
...
--

.. Allow remote access to the Apache Web Server on the system's firewall.
+
[source,subs="verbatim,quotes"]
--
$ *sudo firewall-cmd --add-service=http --permanent*
success
$ *sudo firewall-cmd --reload*
success
--

.. Install the RPM-OSTree and the lower level OSTree tooling on the web server machine, because you will need to perform maintenance on the OSTree repositories you store on it.
+
[source,subs="verbatim,quotes"]
--
$ *sudo yum install -y rpm-ostree ostree*
...
Complete!
--

4. Back to your _development machine_, check that you have access to the web server machine and copy the edge commit image, generated in the xref:ch1-build:s8-compose-lab.adoc[previous lab], to the _web server machine_.

.. Check that the web server is up by using a web browser or any web client to access the default welcome page from the Apache Web Server.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com*
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
        <head>
                <title>Test Page for the HTTP Server on Red Hat Enterprise Linux</title>
...
--

.. Copy the edge commit image to your home directory on the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *scp $UUID-commit.tar servera.lab.example.com:~*
...
--

5. Switch again to your _web sever machine_ and publish the OSTree commit in the web server content directory.

.. Extract the OSTree commit to the web server content directory.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ls -1*
_{compose-uuid-httpd-v1-aaaaaaaaaaaa}_-commit.tar
$ *sudo tar xf ~/$UUID-commit.tar -C /var/www/html*
--
+
IMPORTANT: Extracting an edge commit image only works for initializing a new OSTree repository with a single branch and commit. If you must add multiple edge images to the same OSTree repository, or you need to add updates to an edge image, you must use the `ostree init` and `ostree pull-local` commands.

.. Ensure the OSTree repository contents are accessible to the `apache` user and have correct SELinux labels.
+
[source,subs="verbatim,quotes"]
--
$ *ls -lZ /var/www/html*
total 5
-rw-r--r--. 1 root root unconfined_u:object_r:httpd_sys_content_t:s0 553 Sep  6 18:07 compose.json
drwxr-xr-x. 7 root root unconfined_u:object_r:httpd_sys_content_t:s0 102 Sep  6 18:07 repo
--

.. If you need, change file permissions and SELinux labels.
+
[source,subs="verbatim,quotes"]
--
$ *sudo chmod -R a+X /var/www/html*
$ *sudo restorecon -R /var/www/html*
--

.. Remove the compose metadata, because you do not need it to serve OSTree content.
+
[source,subs="verbatim,quotes"]
--
$ *sudo rm /var/www/html/compose.json*
--

6. Back to your _development machine_, verify that a remote client can access the remote OSTree repository.
+
Check that a remote client can read the OSTree repository configuration file. This way, you don't need to setup a local OSTree repository on the development machine and configure it with a remote that points to the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/config*
[core]
repo_version=1
mode=archive-z2
--

7. If you wish, you can now close the SSH connection to the web server machine and its terminal.

Now you have a web server configured to serve an OSTree repository and you have an edge system image stored on that OSTree repository.

== Next Steps

Before proceeding to test the edge image using a virtual machine, the next activity demonstrates how to publish additional edge images to the remote OSTree repository we just created.

