:time_estimate: 6
:compose-uuid-mysql-v1-aaaaaaaaaaaaaa: ff15f8cd-21da-489a-87d0-bb39df4b79ad

= Lab: Publish Edge Images on Remote OSTree Repositories

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Publish an edge commit image from Image Builder  in an existing remote OSTree repository so it is available to edge devices.

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your test machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a _web server machine_ which serves an OSTree repository. Make sure you web server was configured and verified by following the instructions from the xref:s2-ostree-lab.adoc[previous lab].

These instructions were tested on RHEL 9.5 but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you will start SSH sessions to the `servera` VM from the same user. If not, please adapt the instructions to your test environment.

You will perform some steps of this lab on your _development machine_ and some steps on your _web server machine_. Pay attention to the instructions at each step, when they request that you switch to a different machine!

== Instructions

// Switch everywhere to use the hostname in the prompt? No ]

// It seems silly having to extrat the tar before pull-local but I didn't find a better way. Using ostree commit --tree didn't work (a VM can't boot from the commit)

1. On your _development machine_, verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-118-1.el9.x86_64
...
--

.. Check that a remote client can access the OSTree repository in the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/config*
[core]
repo_version=1
mode=archive-z2
--

.. Open a web browser and navigate to the path `/repo/refs/heads` of the web server. This directory tree lists all branches of an OSTree repository. You should see a branch with the path `rhel/9/x86_64/edge`.
+
Alternatively, fetch the current commit ID of that branch from the command line. Your will get a different ID:
+
[source,subs="verbatim,quotes,attributes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/edge*
{commit-httpd-v1}
--
+
Remember that the commit ID of an edge image in an OSTree repository does *not* match its UUID in the Image Builder service.

2. Get a blueprint to build a second edge system image, running a different application than the image used in previous exercises. The first image runs an Apache Web Server, and this second image runs a MySQL database.

.. Download the `rhel9-mysql.toml` blueprint file from the https://github.com/RedHatQuickCourses/rhde-build-samples/tree/main[course samples] git repository.
+

.. Review the blueprint, it just installs and enables a MySQL server, which is uninitialized.
+
[source,subs="verbatim,quotes"]
--
$ *less rhel9-mysql.toml*
include::1@samples:blueprints:example$rhel9-mysql.toml[]
--

.. Push the blueprint to the Image Builder service, and verify that both the first blueprint, from xref:ch1-build:s6-blueprint-lab.adoc[a previous lab], and the second blueprint are available.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push rhel9-mysql.toml*
$ *composer-cli blueprints list*
rhel9-edge
rhel9-mysql
--

3. Build an edge commit image from the MySQL bluerprint.

.. Create a compose from the second blueprint, but specify a different OSTree branch name for this compose, using the `--ref` option, else it will be considered by edge devices just another version of the first image, instead of a different image.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose start-ostree rhel9-mysql edge-commit --ref rhel/9/x86_64/db*
Compose {compose-uuid-mysql-v1-aaaaaaaaaaaaaa} added to the queue.
--
+
Remember that the UUID of the compose will be different for you.

.. To ease the following steps, copy and paste the UUID of the compose, from the output of the previous command, to a shell variable.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=_{compose-uuid-mysql-v1-aaaaaaaaaaaaaa}_*
--

.. Wait until your compose has finished successfully. You may need to repeat the following command multiple times.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list*
ID                                     Status     Blueprint         Version   Type
{compose-uuid-mysql-v1-aaaaaaaaaaaaaa}   RUNNING    rhel9-mysql       0.0.1     edge-commit
...
$ *composer-cli compose list*
ID                                     Status     Blueprint         Version   Type
{compose-uuid-mysql-v1-aaaaaaaaaaaaaa}   FINISHED   rhel9-mysql       0.0.1     edge-commit
...
--

.. Download the edge commit image from your compose.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose image $UUID*
{compose-uuid-mysql-v1-aaaaaaaaaaaaaa}-commit.tar
--

.. Copy the edge commit image to your home directory on the _web server machine_.
+
[source,subs="verbatim,quotes"]
--
$ *scp $UUID-commit.tar servera.lab.example.com:~*
...
--

4. Switch to your _web server machine_ and publish the edge commit image on its OSTree repository.

.. On another terminal, start an SSH session on your web server machine (`servera`), and copy the shell variable from the first terminal.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=_{compose-uuid-mysql-v1-aaaaaaaaaaaaaa}_*
--

.. Extract the edge commit image to a temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf ~/$UUID-commit.tar -C delete-me*
--

.. Before proceeding, ensure your new edge commit image uses a different branch name than the edge commit image that's already in the OSTree repository of the web server.
+
[source,subs="verbatim,quotes"]
--
$ *ostree --repo=delete-me/repo refs*
rhel/9/x86_64/db
$ *ostree --repo=/var/www/html/repo refs*
rhel/9/x86_64/edge
--

.. Copy the edge commit image to the web server by pulling from the OSTree repository in the temporary directory to the OSTree repository in web server document root. Notice that you need root privileges to write to web server files.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ostree pull-local --repo=/var/www/html/repo delete-me/repo*
446 metadata, 1574 content objects imported; 0 bytes content written
--

.. Check that now there are two edge images (two branches) on the OSTree repository on the web server.
+
[source,subs="verbatim,quotes"]
--
$ *ostree refs --repo=/var/www/html/repo*
rhel/9/x86_64/edge
rhel/9/x86_64/db
--

.. You can now delete the temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *rm -rf delete-me*
--

5. Back to your _development machine_, verify that a remote client can fetch the new edge commit image from the web server by checking that you can fetch the commit ID of the new OSTree branch.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/db*
{commit-mysql-v1}
--
+
Your commit ID will be different than the one above.

6. If you wish, you can now close the SSH connection to the web server machine and its terminal.

Now you have a web server configured to serve an OSTree repository with contains two different edge system images.

== Next Steps

The next activity will provision local VMs from the two edge system images, using either the standard RHEL installation media or a customized edge installer image.


