:time_estimate: 12

= Introduction to Red Hat Device Edge

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Understand how edge devices differ from traditional Linux servers and the features of Red Hat Enterprise Linux (RHEL) for Edge.


WARNING: Work In Progress

== What is Red Hat Device Edge

Red Hat Device Edge is a software and support subscription that bundles three components:

. Red Hat Enterprise Linux (RHEL) and its RHEL for Edge feature.
. Red Hat build of MicroShift.
. Red Hat Ansible Automation Platform.

// Image processed by Inkscape 1.3.2 is not displaying correctly on Fedora 40 CSB
// Had to use Inskscape from a RHEL 9.4 VM to get SVGs that work

image::s1-devices-fig-1.svg[title="Components of Red Hat Device Edge"]

All of these three components can be purchased as part of a number of other subscriptions from Red Hat. For example, RHEL and Ansible are frequently purchaged as their own subscriptions, instead of as part of a bundle, and MicroShift is also available as part of Red Hat OpenShift Container Platform and Red Hat OpenShift Plus.

In the end, you may purchage Red Hat Device Edge to use the RHEL for Edge feature in an army of small edge devices, but you could also find out that your edge machines are "large" and best suited to another subscription which also includes RHEL, OpenShift, and other Red Hat products, and still take advantage of the RHEL for Edge feature.

In this course, we focs on the technical capabilities provided by RHEL for Edge, while other courses in this learning path focus on MicroShift and Ansible management of edge devices.

== What is RHEL for Edge

RHEL for Edge offers a number of technical capabilities desgined to make it more productive and cost-effective to provision and manage a larger fleet of edge devices, compared to a relatively smaller fleet of office workstations and corporate servers. These capabilities also addresses the common constraints on the availability of good network connectivity and highly skilled IT personel at edge sites.

The RHEL for Edge feature relies on the following components of Red Hat Enterprise Linux:

Image Builder::

The Image builder tool takes a blueprint as input and outputs different types of operating system images. Those images can be either traditional package-based images or single-system images, which it calls edge images, and those images can be deployed by means of physical media, network boot, or as cloud provider native images.

OSTree::

The OSTree technology enables deploying and updating bootable operating system images as atomic units, with eficient use of both disk space and network bandwidth. OSTree is also capable of preserving the local state of a device, including both operating system configuration and application data, when updating a system image.

RPM-OSTree::

The RPM-ostree technology is a bridge between the world of traditional Linux package managers and image-based deployments. It enables building OSTree operating system images from RPM packages and, optionally, adding RPM packages as an extension layer into an OSTree deployment.

Green Boot::

The Green Boot technology enables performing healh checks at system boot and, if those checks detect any issue, rolling back the system to a previous system image. Green Boot ensures that system updates can be aplied safely and reliably, without intervention from IT personal in case of issues.

FIDO Device Onboard (FDO)::

The FDO standard enables installing secrets and configuration data into a device so that the device is able to connect and interact securely with cloud and edge management platforms and with central IT systems. RHEL for Edge supports many alternatives to FDO for performing local device and site configuration, such as Kickstart, cloud-init, and ignition, but the FDO standard is gaining traction in the Internet-of-Things (IoT) commnuity and vendors.

Notice that the componentes of RHEL for Edge depend on each other, for example: Green Boot can only rollback a system update because RPM-OSTree keeps the previous OSTree image on disk, unchanged.

In this course, we focus on using the Image Builder and RPM-OSTree components of RHEL for Edge to deploy and update edge devices. Other courses will teach the use of Green Boot and FDO to automate system image rollback and device onboarding.

To understand how these componments address the needs of edge devices, you must consider how edge devices differ from traditional office workstations and data center servers.

== What is an Edge Device

Edge devices, sometimes called edge endpoints, edge gateways, and edge servers, come in varying shapes and forms. RHEL for Edge is not designed to support any kind of edge device, it is designed to run in devices which are close in hardware architecture to standard personal computers and servers. It benefits from the large ecosystem of software and hardware certified for RHEL and the fact that the economy of edge devices got to a point where a "standard computer" is cost-effective and brings a lot more flexibility and power than a custom processor and interface design.

[ illustrative figure of edge systems, workstations, and servers ]

For example you cannot run RHEL directly in a surveilance camera, even if many security cameras do indeed run Linux. But you could run RHEL in edge devices that monitor the video feed from a surveilance camera (or from multiple cameras) to detect potential security threats and fire an alarm to call security or the police.

A similar edge device could use a video camera to perform quality control in a factory, identifying defective pieces and reducing the need for human inspection, and also reroute the defective pieces for either disposal or recycling without manual intervention.

Now imagine that the same edge device controls a robotic arm with a spray gun: instead being pre-programmed with a fixed path for only a few pieces known in advance, an edge device could adapt and optimize the paint process based on the specific piece it sees.

Each of the scenarios above requires some specialized hardware, but they are more about the application software which controls the hardware than about custom chips and perfipherals. Having a common and standard foundation for that software, based on Red Hat Device Edge, reduces the development and maintenance effort.

There are much more potential scenarios for edge devices than we can describe here. Most times, edge devices will co-exist with more traditional computers in the same site, or will connect to traditional computers in remote sites such as corporate headquarters or a regional distribution center. For more information on the aplicability of RHEL for Edge and Red Hat Device Edge to different edge scenarios, we invite you to explore https://www.redhat.com/en/products/edge/hatville[HatVille, the miniature city where edge computing comes to life].

Edge devices where you deploy RHEL for Edge could look like standard computers, maybe in a rugged and smaller form factory, which connect to varying kinds of sensors and machinery. They could also take unique form factors which integrate sensors, servo mechanisms, and other kinds machinery with an Intel or ARM computer in the same box and might not look, from the outside, anything like a "personal computer", despite being built on the same fundamental architecture, processors, chipsets, and peripheral busses.

The following table compares edge devices with more traditional computers to help you distinguish when you might have a case of RHEL for Edge versus a case for traditional RHEL. Parts of it may become quickly outdated as hardware evolve and costs come down, so instead of focus on hard facts, focus on relative differences and check the https://www.redhat.com/en/resources/red-hat-enterprise-linux-subscription-guide[RHEL Subscription Guide] or ask your Red Hat Account Manager for pricing and elibility of the many edge and non-edge product SKUs.

// Looks like images do not work in tables with Antora or asciidoc :-(

[options="header",cols="1,1, 1"]  
|===
| RHEL for Edge
| RHEL Workstation
| RHEL Server

| Mini-PC, rugged mini-server, and many custom form factors
| desktop or laptop PC
| rack-mounted or blade enclosure

| 1 CPU socket, 1 or 2 CPU cores
| 1 or 2 CPU sockets, 4 to 16 CPU cores
| 2 to many CPU sockets, from dozens to hundreds of CPU cores

| 1.5 to 8 GB of memory
| 4 to 64 GB of memory
| Hundreds to thousands GB of memory

| Single purpose: Point-of-sales, industrial control, access control
| Multi-purpose: web browsing, spreadsheets, multimedia, etc
| Multi-purpose: databases, ERP, IT automation, etc

| Special-purpose peripherals: bar code readers, device actuators, temperature/humidity sensors, custom key panels, and so on
| Standard peripherals: monitors, qwerty keyboards, mouses, scanners, printers
| Standard peripherals: Ethernet NIC, NVE cards

| Deployed on hazardous environments, exposed to dust, heat, eletromagnetic fields, and heavy machinery
| Deployed on friendly office environments, with stabilized power supply and colling
| Deployed on friendly datacenter environments, with stabilized power supply and colling

| Exposed to end users, customers, and outsiders, frequently in public areas
| Exposed to office employees, protected by corporate access controls
| Locked in server rooms

| Rely on minimal to no infra-structure on edge sites, such as DHCP servers and IP routers
| Depend on extensive infra-structure from corproate IT, such as identity managers, backup appliances, file servers, and remote control
| Depend on extensive infra-structure from corproate IT, such as automated management, certificate servers, CI/CD, storate arrays, and firewalls

| Deployed and maintained by field technicians
| Deployed and maintained by IT support staff
| Deployed and maintained by System Administrators
|===


== Image-Based Versus Package-Based Systems

The main characteristic of RHEL for Edge, from the point of view of a Systems Administrator, is that it is an image-based system, while traditional RHEL is a package-based system. You can use the RHEL Image Builder to build both types of system images, but with RHEL for Edge it builds system images based on RPM-OSTree.

An image-based system manages an entire operating system as a single system image. You do not install or update individual parts of the operating system, like you would do with package-based systems, using a package manager.

Package-based systems require extensive day-2 customizations to install additional packages and edit system configuration files. On the other side, with image-based systems it is expected that most day-2 customizations are already embedded on the system image. This is consistent with the shift-left approaches popular among DevOps and cloud-native practicioners.

The following table compares common actions for deploying and managing traditional RHEL, or package-based RHEL, with RHEL for Edge.

[options="header",cols="1,1"]  
|===
| RHEL for Edge
| Traditional RHEL

| Image-based, using the RPM-OSTree hybrid image and manager with OSTree system images and RPM packages.
| Package-based, using the DNF package manager with RPM packages.

| Either the RHEL installer or the CoreOS installer downloads and extracts a complete OSTree system image at once.
| The RHEL installer downloads and installs many RPM packages one by one.

| Download and deploy a complete OSTree system image, while retaining the previous system image unchanged. You end up keeping the previous system image or switching to the new system image.
| Update individual RPM packages using DNF. You might update some packages and not others, either on purpose, by mistake, or because some package updates could not be downloaded or applied.

| You know the state of the entire system: it corresponds to one and only one of the available system images.
| You can never be sure about the state of a package-based system, as a whole: it could be in any permutation of the many packages and versions available.

| Install all operating system components and applications at once, as part of the system image.
| Install individual operating system components or applications one by one, from individual RPM packages and OCI container images.

| Embed operating system and application configuration files in the system image, and perform minimal local customization or edits, per-device or per-site, as a day-2 activity.
| Edit operating system and application configuration files one by one, as a day-2 activity (after deploying the operating system).

|===

When you create a RHEL cloud instance, for examaple using the AMI or Qcow2 cloud images for RHEL, they depoloy package-based RHEL, which you manage the same way as if you installed from the RHEL installation media. But, with RHEL for Edge, you can create cloud images which deploy image-based systems, even if your cloud instances are not coud edge instances.

The RPM-OSTree technology allows you to add RPM packages to a system installed from an OSTree system image, but it enforces a clear separation between the contents from the system image and the packages (mostly applications) layered over the system image, similar to how Andoid and iOS devices table deploy and update their operating systems independent of applications from the marketplace. Do not abuse from this capability, else you could lose track of the state of each individual edge devices. It exists mostly for development, testing, and troubleshooting of changes that will become part of the next system image.

RHEL for Edge can also consume applications as OCI container images, and update those container images from container registries. This is more manageable than RPM packages because there is an automatic rollback capability from podman and systemd, which is similar to Green Boot with OSTree updates. Anyway, it is usually prefereable to include your application container images in the OSTree system image so you know the state of edge devices corresponds to a system image and nothing else.

When you think about customizations of an edge device, consider how much of it is actually per-device or per-site. You may find that many, if not most, of the day-2 customizations you're used to perform in package-based systems could be included in a system image. For example, the public key of your corporate certificate authority, for secure TLS communications, is a customization that applies to all your edge devices equaly, in all sites. But the IP address of a web proxy is probably per-site.

== Next Steps

// Add links to previous headings on bootc, FDO, ostree, etc

Before learning about the operation of Image Builder and edge image types, you will assess your understanding of how edge sites differ from traditional corporate IT datacenters and cloud IT.

