:time_estimate: 5

= Lab: Create and Manage Blueprints for Edge Images

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Create, validate, and update Image Builder blueprints for building edge images.

WARNING: Work In Progress

== Before you Begin

You need a RHEL machine configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your test machine was configured and verified by following the instructions from the xref:s4-install-lab.adoc[previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`. If not, please adapt the instructions to your test environment.


// Is there any customization worth of showcasing right now? Timezone, keyboard, networking?

== Instructions

1. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

2. Create a minimal blueprint for an edge device and upload it to the Image Builder service.

.. Create a minimal blueprint for a RHEL 9 server in text mode. This blueprint includes no application, on purpose.
+
Use your preferred text editor to create the `rhel9-edge.toml` file with the following contents:
+
[source,subs="verbatim,quotes"]
--
name = "rhel9-edge"
description = "blueprint-rhel9-edge"
version = "0.0.1"
modules = [ ]
groups = [ ]

[customizations]
hostname = "edge"
--
+
You can download the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/blueprints/rhel9-edge.toml[minimal blueprint] from the sample applications repository in GitHub.

.. Upload the blueprint to Image Builder.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push rhel9-edge.toml*
--

.. Verify that the blueprint exists in the Image Builder service storage. Notice that it has no record of the original file name, you identify blueprints by ther `name` attributes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints list*
rhel9-edge
--

.. You can also show the contents of the blueprint as stored in the Image Builder service.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints show rhel9-edge*
name = "rhel9-edge"
description = "blueprint-rhel9-edge"
version = "0.0.1"
...
--

3. Validate that Image Builder service can resolve all dependencies from the blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints depsolve rhel9-edge*
blueprint: rhel9-edge v0.0.1
    acl-2.3.1-3.el9.x86_64
    alternatives-1.20-2.el9.x86_64
    audit-libs-3.0.7-103.el9.x86_64
...
--
+
The list of packages is very long, even for minimal blueprints. It is important to check that there are no error messages in the output.

4. Change the blueprint to add an Apache Web Server. Suppose that your 
original intent was to include the web server as the application on this blueprint, but forgot to do so.

.. Download the blueprint from the Image Builder service to the `rhel9-httpd.toml` file.
+
You could make changes directly to your local file, or grab the original file from version control, but we get it from the Image Builder Service just to show how it can be done.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints save rhel9-edge --filename rhel9-httpd.toml*
--
+
IMPORTANT: Red Hat does NOT recommend that you use Image Builder as the source of truth for blueprints, but only as a temporary storage. Red Hat recommends that you keep your blueprints under version control, using Git or similar software.

.. Use your preferred text editor to change the `rhel9-httpd.toml` file as follows. Make sure you do NOT change its `name` atribute!
+
[source,subs="verbatim,quotes"]
--
name = "rhel9-edge"
description = "blueprint-rhel9-edge"
version = "0.0.1"
modules = [ ]
groups = [ ]

*[[packages]]
name = "httpd"*

[customizations]
hostname = "edge"
--
+
You can download the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/blueprints/rhel9-httpd.toml[changed version of the blueprint] from the sample applications repository in GitHub.

5. Upload and validate the changed blueprint. It is not sufficient to make changes to the local file copy of the blueprint, you must send the changes to Image Builder so you can create images with your changes.

.. First, verify that the current blueprit in the Image Builder service does NOT include the Apache Web Server packages.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints depsolve rhel9-edge | grep httpd*
--

.. Upload the changed blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push rhel9-httpd.toml*
--

.. Verify the blueprint now includes the Apache Web Server.
+
[source,subs="verbatim,quotes"]
--

$ *composer-cli blueprints depsolve rhel9-edge | grep httpd*
    httpd-2.4.53-11.el9_2.4.x86_64
    httpd-core-2.4.53-11.el9_2.4.x86_64
...
--

.. If you made a mistake in the package name, when you changed the blueprint, the pipe to `grep` will NOT hide error messages:
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push rhel9-edge.toml*
ERROR: BlueprintsError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand: toml: line 6 (last key "packages"): type mismatch for blueprint.Package: expected table but found string
--
+
In that case, fix your file and upload the blueprint again.

Now you know the basics of managing blueprints with the Image Builder Service.

== Next Steps

The next activity builds an edge commit image from the blueprint you just created.
