:time_estimate: 5

= Lab: Create and Manage Blueprints for Edge Images

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Create, validate, and update a blueprint for creating edge images.

WARNING: Work In Progress

== Before you Begin

You need a RHEL machine with either the root password or unrestricted sudo, and which was prepared by following the instructios from the xref:s3-install-lab.adoc[previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

// Is there any customization worth of showcasing right now? Timezone, keyboard, networking?

== Instructions

1. Create a minimal blueprint for a RHEL 9 server in text mode. This blueprint includes no application, on purpose.

2. Upload the blueprint to Image Builder.

3. Validate that ImageBuilder can resolve all dependencies from the blueprint.

4. Change the blueprint to add an Apache Web Server. Suppose that your original intent was to include the web server as the application on this blueprint, but forgot to do so.

5. Upload and validate the updated blueprint. It is not sufficient to make changes to the local file copy of the blueprint, you must send the changes to Image Builder so you can create images with your changes.

== Next Steps

The next activity builds an edge commit image from the blueprint you just created.
