:time_estimate: 8

= Create Edge Images as Image Builder Composes

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Understand the different types of edge composes and their usage.

== Image Builder Composes and Images

Creating a compose is the second step in the process of building an edge system image, which can be published into an OSTree repository, and optionally embedded into installation media to provision edge devices.

image::s7-compose-fig-1.svg[title="Composes in an edge device installation and update workflow"]

Remember that a compose is not an actual system image, but the job which produces a system image. If a compose finishes successfully, you can download the image produced by it.

After you build an edge system image, you can optionally create another compose to create a derived installation image, which embeds the edge system image and an RHEL installation program into a bootable media that you can use to provision edge devices without access to network servers.

In this section, we focus on the edge system images and its RPM-OSTree technology. Later in this course, we learn how to create installation images.

== Edge Images and RPM-OSTree

Edge images from Image Builder are based on the OSTree technology, which configures the root file system as read-only. Well, not the true root file system, it's actually a chroot, but you learn about such lower-level details later in this course. In a pure OSTree-based system, you cannot change a system file, not even as root, except by deploying a new system image an rebooting into the new image.

OSTree can keep multiple system images side-by-side in a system, so downloading updates does not affect a running system -- contrast that with RPM package updates, which can alter files that are in use by running processes and produce unpredictable results.

The OSTree technology is not designed to be usable by itself, but to be infrastructure under higher-level Linux distribution tooling. In RHEL, the higher-level infrastructure is RPM-OSTree, which builds OSTree system images from RPM packages.

Image Builder users do not interact with the RPM-OSTree and OSTree tooling directly, at least not to build edge system images. But they must interact with RPM-OSTree to apply updates to edge systems, and they must interact with OSTree directly to publish those updates to remote servers.

== Edge Image Types

All types of edge composes include an OSTree commit as the main payload of their system images. 

The only indispensable type of edge image (or edge compose) from Image Builder is the *edge commit image*. It provides an OSTree system image, called a *OSTree commit*, as a single tar archive.

image::s7-compose-fig-2.svg[title="Edge device installation and update Workflow using an edge commit image"]

You can push the OSTree commit from an edge commit image to a remote OSTree repository, and then edge devices can consume that OSTree commit using the standard RHEL installation media, by means of a custom Kickstart file. This is a suggested workflow for developer testing and CI/CD pipelines and the first one we will perform in activities of this course.

You can also use Image Builder to take an OSTree commit as input and build one of the following kinds of derived edge composes:

Edge installer images::

They include a RHEL installer and an OSTree commit, so you can boot a physical system and install the system image, instead of using the RHEL installation media.

Edge cloud images::

They are directly bootable by cloud or hypervisor platforms and include an already deployed OSTree commit.

Both types of derived edge composes can install an edge system without network access to an OSTree repository.

You can also store either an edge installer image or a standard RHEL installation media in a network boot server and provision edge devices from the network, without using physical boot media.

If you wish to generate an edge installer image, you must create another blueprint which does not specify packages and only specify minimal customizations (or no customizations at all), and provide, as arguments to the compose, a URL to a web server and an OSTree reference from which to pull OSTree commit to embed in the image.

image::s7-compose-fig-3.svg[title="Edge device installation and update Workflow using an edge installer image"]

If you wish to generate an edge cloud image, you also require another blueprint plus a web server URL and an OSTree reference as arguments to the compose.

image::s7-compose-fig-4.svg[title="Edge device installation and update Workflow using an edge cloud image"]

Whatever the boot method and compose type you use for installing an edge system, it requires access to a remote OSTree repository to fetch and deploy system updates. Image Builder cannot build anything similar to an "edge update image", which would boot from local media or network boot and apply a system update. Such a feature is currently in development, as part of the https://www.redhat.com/en/blog/red-hat-vehicle-os-hardware-enablement-program[Red Hat In Vehicle Operating System (RHIVOS)], but it is not supported yet by Image Builder on RHEL.

In fact, all bootable types of edge composers supported by Image Builder are preconfigured with an OSTree remote, which points to an OSTree repository server, except for the *edge container image*. This is a special type of compose designed to run as a Linux container which serves an OSTree commit over HTTP. It is intended as a quick way for a developer to provision a remote OSTree repository to build and test edge installer images, but it is not designed for long-term usage nor for serving system updates.

In this course, you will NOT use edge container composes, you will instead learn how to configure and manage remote OSTree repositories so you can provide system updates to edge devices.

== Naming Composes

Image Builder allows you to give human-readable names to blueprints, but it always identifies composes using UUIDs. A compose refers to a specific build of a blueprint, so there could be multiple composes for the same blueprint. For example, you could build a new compose from an existing blueprint to create a new image with RPM package updates from RHEL.

Image Builder maintains not only the image data for a compose, but also metadata such as package lists and build logs. Using the compose metadata, it is easy to compare two composes from the same blueprint and see what changed in the resulting image.

== Managing Composes

Because a compose is a build job, it takes a few minutes to complete, and you want to monitor its status to check if it is completed successfully or failed. You can also cancel running composes and fetch its build logs and other metadata from either running, finished, or failed composes.

As you create multiple composes, from the same blueprint or different blueprints, sooner or later you will need to delete older composes to conserve disk space in the system running Image Builder. Consider that Image Builder may store multiple copies of the same edge system image, for example as part of a compose that builds an edge commit image and as part of another compose that builds an edge installer image.

== The RPM-OSTree and OSTree Command-Line Tools

RHEL does not provide any Cockpit module or GUI tool to manage OSTree repositories and to update RPM-OSTree systems. These activities must be performed from the command line, using the `rpm-ostree` and `ostree` commands. 

For now, you will use those commands just to inspect the OSTree commit inside an edge commit image and verify it is complete and consistent. Later in this course you will learn about OSTree repository management and we will present those commands in more detail. Then, after you have OSTree repositories configured and populated, you will learn how to create and use edge installer images.

Both the `rpm-ostree` and `ostree` commands follow a similar syntax. For now, you can use the `--help` option with either of them, and their subcommands, to explore their possibilities.

== Next Steps

Now that you know about Image Builder composes and edge image types, the next activity creates a compose for an edge commit image and validates its image for integrity. Later in this course, we will publish the edge commit image in a remote web server and use it to provision a virtual edge device.
