:time_estimate: 5
:compose-uuid-canceled-aaaaaaaaaaaa: 01f3796b-85fd-4383-bbe8-eefc9550acdc

= Lab: Create and Manage Composes for Edge Images

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Create and validate Image Builder composes for building edge images.

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is a member of the `weldr` group. Make sure your _development machine_ is configured and verified by following the instructions from the xref:s4-install-lab.adoc[first lab].

You also need the blueprint that was created and uploaded to the Image Builder service by the xref:s5-blueprint-lab.adoc[previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`. If not, please adapt the instructions to your test environment.

== Instructions

1. Verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Verify that your Image Builder service has a blueprint named `rhe9-edge` that includes the `httpd` package, from the xref:s6-blueprint-lab.adoc[previous lab].
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprint show rhel9-edge*
...
include::1@samples:blueprints:example$rhel9-httpd.toml[lines=8..9]
...
--

2. Build an OSTree commit from the blueprint, but cancel it before it's finished.

.. Start an OSTree compose from the blueprint.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose start-ostree rhel9-edge edge-commit*
Compose {compose-uuid-canceled-aaaaaaaaaaaa} added to the queue
--

.. To ease the following steps, copy and paste the UUID from the previous command output to a shell variable.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=_{compose-uuid-canceled-aaaaaaaaaaaa}_*
--

.. While the Image Builder service builds the image, its compose will show a status of `RUNNING`:
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list*
ID                                     Status    Blueprint    Version   Type
{compose-uuid-canceled-aaaaaaaaaaaa}   RUNNING   rhel9-edge   0.0.1     edge-commit
--
+
If your Image Builder service has many composes, you can filter the listing by appending `finished` or `running` to the `compose list` command.

.. Before a compose finishes running, you can cancel it:
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose cancel $UUID*
$ *composer-cli compose list*
ID                                     Status     Blueprint    Version   Type
{compose-uuid-canceled-aaaaaaaaaaaa}   FAILED     rhel9-edge   0.0.1     edge-commit
--
+
If you took too long to cancel the compose, you can start another one and cancel it. Or just move forward, because you won't need that canceled compose for the remaining of this activity and this course.

3. Build another OSTree commit from the same blueprint, but this time let it finish.

.. Start a new OSTree compose from the blueprint.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose start-ostree rhel9-edge edge-commit*
Compose {compose-uuid-httpd-v1-aaaaaaaaaaaa} added to the queue
--

.. Copy and paste the UUID from the previous command output to a shell variable, overriding its previous value.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=_{compose-uuid-httpd-v1-aaaaaaaaaaaa}_*
--

.. Repeat the command that list composes until you see that the latest changed its status to `FINISHED`.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list*
ID                                     Status     Blueprint    Version   Type
{compose-uuid-canceled-aaaaaaaaaaaa}   FAILED     rhel9-edge   0.1.0     edge-commit
{compose-uuid-httpd-v1-aaaaaaaaaaaa}   FINISHED   rhel9-edge   0.1.0     edge-commit
--

4. Fetch metadata from the compose.

.. Get information such as requested and dependency packages from the compose.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *compose-cli info $UUID | less*
{compose-uuid-httpd-v1-aaaaaaaaaaaa} FINISHED rhel9-edge      0.1.0 edge-commit      
Packages:
    httpd-
Modules:
Dependencies:
    ModemManager-1.20.2-1.el9.x86_64
    ModemManager-glib-1.20.2-1.el9.x86_64
    NetworkManager-1:1.42.2-1.el9.x86_64
...
--    

.. Get the build logs of the compose. There are many errors at the start of the log which are expected and can be ignored.
+
[source,subs="verbatim,quotes"]
--
$ *compose-cli log $UUID | less*
Pipeline build
Stage org.osbuild.rpm
Output:
/usr/lib/tmpfiles.d/colord.conf:1: Failed to resolve user 'colord': No such process
...
Failed to open file "/sys/fs/selinux/checkreqprot": Read-only file system
imported gpg key
imported gpg key
Verifying packages...
Preparing packages...
libgcc-11.3.1-4.3.el9.x86_64
...
--

5. Download and verify the edge commit image from the latest compose.

.. Download the image to your home directory.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose image $UUID*
{compose-uuid-httpd-v1-aaaaaaaaaaaa}-commit.tar
--
+
NOTE: You could use the `--filename` option to specify a name for the image file, instead of using the default generated name based on the UUID of its compose.

.. Extract the image contents to a temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf $UUID-commit.tar -C delete-me*
--

.. Check that the `rpm-ostree` command can use the temporary directory as an OSTree repository and list RPM packages inside the image.
+
[source,subs="verbatim,quotes,attributes"]
--
$ rpm-ostree db list rhel/9/x86_64/edge --repo=delete-me/repo
ostree commit: rhel/9/x86_64/edge ({commit-httpd-v1})
 ModemManager-1.20.2-1.el9.x86_64
 ModemManager-glib-1.20.2-1.el9.x86_64
 NetworkManager-1:1.42.2-1.el9.x86_64
...
--

6. You can now delete the temporary directory, or leave it around for the next activity.
+
[source,subs="verbatim,quotes"]
--
$ *rm -rf delete-me*
--

Now you know the basics of managing composes and building images with the Image Builder service.

== Next Steps

The next activity, in the next chapter, pushes the edge commit image to an OSTree repository, making it available to edge systems, and in later activities you provision a local virtual machine, as a stand-in for an edge device, from that OSTree repository.
