:time_estimate: 5

= Lab: Boot Edge VMs from Remote OSTree Repostories

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Boot a test VM from an OSTree commit in a remote OSTree repository.

WARNING: Work In Progress

== Before you Begin

You need a development machine with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your test machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You need a second machine to run a web server that serves OSTree repositories. Make sure that machine was configured and verified by following the instructions from xref:ch2-publish:s2-ostree-lab.adoc[a previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. If not, please adapt the instructions to your test environment.

== Instructions

1. On your test machine, verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Check that a remote client can access the OSTree repository in the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/config*
[core]
repo_version=1
mode=archive-z2
--

.. Check that you can get the current commit ID the OSTree branch with the httpd edge system image that you created in xref:ch2-publish:s2-ostree-lab.adoc[a previous lab]. Your will get a different ID:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/edge*
4afeda6a96ec8b2c263b6965a9c3f92db1db2436ae1e1233da70b7776fc6137b
--

2. Install the libvirtd tools and its Cockpit module.

.. Install the "Virtualization Host" package group to get the libvirtd, KVM, and Qemu daemons and tools.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf group install -y "Virtualization Host"*
...
Complete!
$ *dnf install -y cockpit-machines*
...
Complete!
--

.. Grant an unprivileged user with permission to create and manage KVM/Qemu virtual machines (VMs).
+
[source,subs="verbatim,quotes"]
--
$ *sudo groupmod libvirt -a -U student*
--

3. Create and publish a kickstart file which points to the OSTree repository on the web server.

.. Using your preferred text editor, create a file named `rhel9-httpd.ks` with the following contents:
+
[source,subs="verbatim,quotes"]
--
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text

zerombr
clearpart --all --initlabel
autopart --type=plain
rootpw --lock
user --name=core --group=wheel --password=redhat123

reboot

network --bootproto=dhcp 
ostreesetup --nogpg --osname=rhel --remote=edge --url=http://servera.lab.example.com/repo/ --ref=rhel/9/x86_64/edge
--
+
You can also downlod the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/ks/rhel9-httpd.ks[kickstart file] from sample applications repository in GitHub.
+
Most lines on that kickstart file can be changed according to your needs, and real-world deployments would include items such as SSH keys for remote management. The important piece is the `ostreesetup` command, which directs Anaconda to download the latest commit from a remote OSTree repository using HTTP.

.. Copy the Kickstart file to your home directory on the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *scp rhel9-httpd.ks servera.lab.example.com:~*
...
--

4. Switch to your web sever machine and publish the kickstart file and the OSTree commit in the web server content directory.

.. Copy the kickstart file to the web server content directory.
+
[source,subs="verbatim,quotes"]
--
$ *ls -1*
_575d8ddc-2902-4de3-a0d5-82f5f194f5d8_-commit.tar
rhel9-httpd.ks
$ *sudo cp rhel9-httpd.ks /var/ww/html*
--

.. Ensure that the kickstart file is acessible to the `apache` user and have correct SELinux labels.
+
[source,subs="verbatim,quotes"]
--
$ *ls -lZ /var/www/html*
total 5
drwxr-xr-x. 7 root root unconfined_u:object_r:httpd_sys_content_t:s0 102 Sep  6 18:07 repo
-rw-r--r--. 1 root root unconfined_u:object_r:httpd_sys_content_t:s0 317 Sep  6 18:07 rhel9-httpd.ks
--

.. If you need, change file permissions and SELinux labels.
+
[source,subs="verbatim,quotes"]
--
$ *sudo chmod -R a+X /var/www/html*
$ *sudo restorecon -R /var/www/html*
--

5. Back to your development machine, verify that a remote client can access the kickstart file.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/rhel9-httpd.ks*
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --isUtc
...
--

6. Create a RHEL VM which boots from the RHEL installation ISO and fetches an edge commit image from a web server.

.. Download the standard RHEL installation ISO from the customer portal, or grab a copy in the classroom environment at [ADD LINK]. Ensure you have a complete and consistent ISO in the `/home/student/Downloads/rhel-9.4-x86_64-boot.iso` file before proceeding.

.. Create a local VM, with a serial console, which uses the kickstart file from previous steps. Usign a serial console makes it easy to capture installation and boot messages for troubleshooting.
+
The following is a long command, it is broken into multiple lines for readability.
+
[source,subs="verbatim,quotes"]
--
$ *virt-install --name edge-test-1 --os-variant rhel9.2 \
--memory 4096 --vcpus 2 --disk size=40 --graphics=none \
--location /home/student/Downloads/rhel-9.4-x86_64-boot.iso \
--extra-arg inst.ks=http://servera.lab.example.com/rhel9-httpd.ks \
--extra-arg console=ttyS0 -v*
--
+
NOTE: You must use `--location` instead of `--cdrom` to be able pass kernel arguments with `--extra-args`. Else you will be required to use the Grub menu, interactively, to add a reference to the kickstart file.

.. Wait until the installation finishes and you get a login prompt on the VM. It is expected that the VM reboots once during its installation. Log in as user `core` with password `redhat123`.
+
[source,subs="verbatim,quotes"]
--
Edge login:
--

.. If the VM creation fails, and you must try again, stop and remove the VM before retrying the previous step.
+
[source,subs="verbatim,quotes"]
--
$ *virsh destroy edge-test-1*
Domain 'edge-test-1' destroyed
$ *virsh undefine edge-test-1*
Domain 'edge-test-1' has been undefined
--

[ Add steps to check the local VM, its local OSTree repo, commit, remote, and deployed commit? ]

You can leave that VM running, or stop it and restart in a future lab, when we apply updates to edge images.

== Next Steps

The next activity builds an edge installer image and boots another local VM from it, demonstrating another method to provision edge devices.
