:time_estimate: 11

= Lab: Boot Test VMs from Edge Installer Images

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Build an edge installer image and boot a test VM from it.

WARNING: Pending SME Review & Proofreading

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your development machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a _web server machine_ which serves an OSTree repository. Make sure that machine was configured and verified by following the instructions from xref:ch2-publish:s2-ostree-lab.adoc[a previous lab].

Finally, you need the database image that you created and published in xref:ch2-publish:s2-ostree-lab.adoc[another lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. If not, please adapt the instructions to your test environment.

You will perform most steps in this lab from your _development machine_. You have no need to log in on the _web server_ machine if it was prepared correctly by previous labs. You will also perform a few steps from a _database VM_ that you will create as part of this lab.

== Instructions

// have the user created on the blueprint instead of by kickstart? use a name other than "core", and mention SSH keys

// See customizations.installer.kickstart in https://osbuild.org/docs/user-guide/blueprint-reference maybe I can embed the kick start on the blueprint, instead of altering the ISO after generation... if this is available on RHEL 9.4 or later

// Review the blueprint vs kickstart: where it's best to create the "core" user? Replace with a "dba" user? Check also sudo access!

// This lab, using the installer image, might be a good one to use Cockpit begining to end ... or save it for the "simplifed installer image (next tentative lab?)"


1. Verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Check that a remote client can access the OSTree repository in the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/config*
[core]
repo_version=1
mode=archive-z2
--

.. Check that you can get the current commit ID the OSTree branch with the httpd edge system image that you created in xref:ch2-publish:s3-pull-local-lab.adoc[a previous lab]. You will get a different ID:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/db*
12a22681baff58184e22ebc3e189453ed18f0984727c81311781021ccab899a1
--
+
Pay attention to the final path element of the URL, which should be "db".

.. Check that you can manage local VMs, and that there's a VM left from the xref:s2-boot-lab:[previous lab].
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name          State
---------------------------
 1    edge-test-1   shut-off
--
+
It's fine the existing VM displays a status of "running" instead of "shut off". You do not need the existing VM for this lab, but you will use it in a future lab.

2. Create an edge installer image.

.. Use your preferred text editor to create a blueprint for the edge installer image, in the `mysql-installer.toml` file, with the following contents.
+
[source,subs="verbatim,quotes"]
--
name = "mysql-installer"
description = "blueprint-mysql-installer"
version = "0.0.1"
--
+
You can also download the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/blueprints/mysql-installer.toml[installer blueprint] from the sample applications repository in GitHub.

.. Upload the blueprint to the Image Builder service.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push mysql-installer.toml*
$ *composer-cli blueprints list*
rhel9-edge
rhel9-mysql
mysql-installer
--

.. Build an edge installer image, using the blueprint you just uploaded, referring to the edge commit image that was published in a web server in a xref:ch2-publish:s3-pull-local-lab.adoc[previous lab].
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose start-ostree mysql-installer edge-installer --ref rhel/9/x86_64/db --url http://servera.lab.example.com/repo/*
Compose 7a5036e1-4037-4edc-82ff-4c632c0a84fc added to the queue
--

.. If you use an invalid blueprint, that adds packages or defines invalid customizations to an edge installer image, you will get an error similar to the following:
+
[source,subs="verbatim,quotes"]
--
ERROR: ManifestCreationFailed: failed to create osbuild manifest: unsupported blueprint customizations found for boot ISO image type "edge-installer": (allowed: User, Group)
--

.. Copy the UUID of your compose, from the previous command, to a shell variable.
+
[source,subs="verbatim,quotes"]
--
$ *UUID=7a5036e1-4037-4edc-82ff-4c632c0a84fc*
--

.. Wait until the composition finishes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose list*
ID                                     Status     Blueprint         Version   Type
7a5036e1-4037-4edc-82ff-4c632c0a84fc   RUNNING    mysql-installer   0.0.1     edge-installer
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
$ *composer-cli compose list*
ID                                     Status     Blueprint         Version   Type
7a5036e1-4037-4edc-82ff-4c632c0a84fc   FINISHED   mysql-installer   0.0.1     edge-installer
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   mysql-edge        0.0.1     edge-commit
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
--

.. Download the edge installer image. You should get an ISO file.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose image $UUID*
7a5036e1-4037-4edc-82ff-4c632c0a84fc-installer.iso
--

3. Inspect your edge installer image.

.. Mount the ISO file in a temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir temp-iso*
$ *sudo mount -o loop,ro $UUID-installer.iso temp-iso*
--

.. Check that the ISO contains an OSTree repository and a kickstart file.
+
[source,subs="verbatim,quotes"]
--
$ *ls temp-iso/*
EFI  images  isolinux  osbuild.ks  ostree
$ *ls temp-iso/ostree/repo/*
config  extensions  objects  refs  state  tmp
$ *cat temp-iso/osbuild.ks*
ostreesetup --osname=rhel --url=file:///run/install/repo/ostree/repo --ref=rhel/9/x86_64/db --nogpg
--

.. Find the label of the ISO image, you will need it for the next steps. Copy the argument of the `-l` option to a shell variable
+
[source,subs="verbatim,quotes"]
--
$ *grep search temp-iso/EFI/BOOT/grub.cfg*
search --no-floppy --set=root -l 'RHEL-9-2-0-BaseOS-x86_64'
$ *LABEL=RHEL-9-2-0-BaseOS-x86_64*
--

.. Extract the ISO contents into another temporary directory
+
[source,subs="verbatim,quotes"]
--
$ *mkdir new-iso*
$ *sudo tar cf - -C temp-iso . | tar xf - -C new-iso*
--

.. Unmount the ISO.
+
[source,subs="verbatim,quotes"]
--
$ *sudo umount temp-iso*
--

4. Replace the kickstart in the edge installer image with one designed for unattended installation.

.. Verify that you have the `mkisofs` command. If you don't, install the `xorriso` package. It's fine if have a different version than shown below.
+
[source,subs="verbatim,quotes"]
--
$ *mkisofs --version*
xorriso 1.5.4 : RockRidge filesystem manipulator, libburnia project.
...
--

.. Create a new kickstart file with uses the same `ostreesetup` command from the minimal kickstart file you see in the edge installer image, but adds other commands so it can run unattended. Save the new kickstart file as `rhel9-mysql-installer.ks`
+
[source,subs="verbatim,quotes"]
--
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --isUtc
text

zerombr
clearpart --all --initlabel
autopart --type=plain
rootpw --lock
user --name=core --group=wheel --password=redhat123

reboot

network --bootproto=dhcp
ostreesetup --osname=rhel --url=file:///run/install/repo/ostree/repo --ref=rhel/9/x86_64/db --nogpg
--
+
You can also download the contents of the https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/ks/rhel9-mysql-installer.ks[new kickstart file] from the course samples repository in GitHub.

.. Copy your custom kickstart file over the kickstart file on the edge installer image.
+
[source,subs="verbatim,quotes"]
--
$ *cp rhel9-mysql-installer.ks new-iso/osbuild.ks*
--

.. Build a new iso. If you notice that the following command specifies the `-no-emul-boot` option twice, this is *not* a mistake! You really need the two of them.
+
[source,subs="verbatim,quotes"]
--
$ *mkisofs -o new-installer.iso -b isolinux/isolinux.bin -J -R -l -c isolinux/boot.cat \
-no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot \
-graft-points -joliet-long -V "$LABEL" new-iso*
...
Writing to 'stdio:new-installer.iso' completed successfully.
--

.. Ensure that your bootable ISO is compatible with UEFI firmware.
+
[source,subs="verbatim,quotes"]
--
$ *isohybrid --uefi new-installer.iso*
isohybrid: Warning: more than 1024 cylinders: 2220
isohybrid: Not all BIOSes will be able to boot this device
--

.. Mount the new ISO in a temporary directory and check that it contains the customized kickstart file, then unmount it.
+
[source,subs="verbatim,quotes"]
--
$ *sudo mount -o loop,ro new-installer.iso temp-iso*
$ *cat temp-iso/osbuild.ks*
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --isUtc
...
$ *sudo umount temp-iso*
--

5. Create a _database VM_ that boots from the edge installer image.

.. Create a local VM using the edge installer image from the previous steps. You can choose one of the following:
+
* Use a graphical boot, from a virtual CD-ROM reader.
+
NOTE: You must do this from a graphics desktop.
+
[source,subs="verbatim,quotes"]
--
$ *virt-install --name edge-db-1 --os-variant rhel9.2 --memory 4096 --vcpus 2 --disk size=40 \
--cdrom /home/student/new-installer.iso -v*
--
+
* Use a virtual serial console and direct kernel loading, plus a reference to kickstart in the ISO image.
+
NOTE: You can do this from a secure shell session.
+
[source,subs="verbatim,quotes"]
--
$ *virt-install --name edge-db-1 --os-variant rhel9.2 --memory 4096 --vcpus 2 --disk size=40 \
--location /home/student/new-installer.iso --graphics=none --extra-arg console=ttyS0 \
--extra-arg inst.ks=hd:LABEL=$LABEL:/osbuild.ks -v*
--
+
* If you are used to managing Libvirt VMs using Cockpit, feel free to perform VM creation and other tasks using its web UI.
+

.. Wait until the installation finishes and you get a login prompt on the VM. It is expected that the VM reboots once during its installation. Log in as user `core` with password `redhat123`. [ review for  RHEL 9.4 ]
+
[source,subs="verbatim,quotes"]
--
Red Hat Enterprise Linux 9.2 (Plow)
Kernel 5.14.0-284.11.1.el9_2.x86_64 on an x86_64

edge-db login: *core*
Password: 
[core@edge-db ~]$ 
--

6. On your _database VM_, check it is an image-based system using RPM-OStree.

.. Use the `rpm-ostree` command to see its deployed branch and commit.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/db
                  Version: 9.2 (2024-09-06T22:07:45Z)
                   Commit: 12a22681baff58184e22ebc3e189453ed18f0984727c81311781021ccab899a1
--
+
Notice that the commit ID you see matches the one from the `curl` command at the beginning of this lab.

.. Verify that the local OSTree repository is *not* connected to a remote repository yet. You will need to configure a remote before you can update this edge VM.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *ostree remote list --show-urls*
rhel  file:///run/install/repo/ostree/repo
--

.. If you wish, you can explore the file system inside the _database VM_. You should see the same mounts you already saw in the xref:s2-boot-lab.adoc[previous lab]. Different types of edge images should produce the same file system layout.

7. On your _database VM_, check that there is a MySQL database running.

.. Verify that the `mysqld` Systemd service is enabled and active
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *systemctl is-active mysqld*
active
--

.. Verify that the MySQL database inside the VM containers only the standard system databases.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *sudo mysqlshow*
+--------------------+
|     Databases      |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
--
+
Later in this course, you will update your database image to include a starter database.

8. Return to your _developer machine_, and optionally stop your _database VM_.
+
WARNING: Do not delete (`virsh undefine`) your _database VM_, you will use it during the next chapter to perform system updates.

.. Detach from the serial console of the VM by typing `Ctrl+]`.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *^]*
$
--

.. Optionally, stop the _database VM_. You will still use that VM in a future lab, when we apply updates to edge images.
+
[source,subs="verbatim,quotes"]
--
$ *virsh destroy edge-db-1*
Domain 'edge-db-1' destroyed
$ *virsh list --all*
 Id   Name          State
---------------------------
 1    edge-test-1   shut-off
 2    edge-db-1     shut-off
--

.. If you had issues with booting or accessing your _database VM_, please review the xref:s2-boot-lab.adoc[previous lab] for Libvirt troubleshooting hints using the `virsh` command. It may also help to try a different VM creation method, for example, if you used `--location`, try using `--cdrom`.

You just learned how to create an edge installer image and boot a test VM from it. Notice that, unlike the xref:s2-boot-lab.adoc[previous lab], you only accessed the _web server machine_ to create the edge installer image but didn't need it to create a test VM.

== Next Steps

The final round of activities in this course will update the system images on both local VMs, to demonstrate how to build and apply system updates to edge devices.

// Could include a third Lab that uses a simplified edge installer image, but I don't see much value, it would perform the same steps with a slightly different bleprint. It would be more interesting if I had device or site customizations to apply with ignition or a sample application
