:time_estimate: 5

= Lab: Boot Edge VMs from Edge Installer Images OSTree

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Build an edge installer image and boot a test VM from it.

WARNING: Work In Progress

== Before you Begin

You need a RHEL machine configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your test machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You need a second machine to run a web server that serves OSTree repositories. Make sure that machine was configured and verified by following the instructions from xref:ch1-build:s7-ostree-lab.adoc[the previous lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. If not, please adapt the instructions to your test environment.

== Instructions

[ have the user created on the blueprint instead of by kickstart? use a name other than "core", and mention SSH keys ]

1. On your test machine, verify that you have the prerequisites from previous labs.

.. Verify that TBD
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

2. Install the libvirtd tools and its Cockpit module.

.. Install the "Virtualization Host" package group to get the libvirtd, KVM, and Qemu daemons and tools.
+
[source,subs="verbatim,quotes"]
--
$ sudo dnf group install -y "Virtualization Host"
$ dnf install -y cockpit-machines
--

.. Grant an unprivileged user with pemrission to create and manage virtual machines (MVs).
+
[source,subs="verbatim,quotes"]
--
$ sudo groupmod libvirt -a -U student
--

3. Create a RHEL VM which boots from the RHEL installation ISO and fetches an edge commit image from a web server.
+
*UPDATE:* second attempt now works, thanks to fixes to kickstart (autopart --type=plain). Now to find out how to put that entry on the kickstart for the installer image... and if I still need those for RHEL 9.4 and later.

.. 1st attempt, from product docs.
+
[source,subs="verbatim,quotes"]
--
$ virt-install \
--name edge-test-1 \
--memory 2048 \
--vcpus 2 \
--disk path=edge-test-1.qcow2,format=qcow2,size=8 \
--os-variant rhel9.0 \
--cdrom /home/student/Downloads/rhel-9.4-x86_64-boot.iso
--
+
Edit the kernel manually entry by appending:
+
[source,subs="verbatim,quotes"]
--
inst.ks=http://servera.lab.example.com/rhel9-httpd.ks
--

.. 2nd attempt, from HOL007.
+
[source,subs="verbatim,quotes"]
--
$ virt-install \
--name edge-test-1 \
--memory 4096 \
--vcpus 2 \
--disk size=40 \
--os-variant rhel9.2 \
--location /home/student/Downloads/rhel-9.4-x86_64-boot.iso \
--graphics=none \
--extra-args inst.ks=http://servera.lab.example.com/rhel9-httpd.ks \
--extra-arg console=ttyS0 -v
--
+
If I use --cdrom instead of --location I get: ERROR    Kernel arguments are only supported with location or kernel installs.

.. Both attempts at using a custom kickstart with an edge commit image result in VMs that, after reboot, stay forever on "A start job is running for…rhel-swap/rhel-boot".
+
They seem to deploy the ostree commit, from boot messages and the apache access log. I have no clue why they cannot finish installation. :-(

4. Cleaning up test VMs up between each attempt.
+
[source,subs="verbatim,quotes"]
--
$ virsh destroy edge-test-1
Domain 'edge-test-1' destroyed
$ virsh undefine edge-test-1
Domain 'edge-test-1' has been undefined
--

5. Create an edge installer image.
+
PENDING: Add a custom kickstart to the edge installer image, because the one from Image Builder does NOT work as-is.

.. Create a blueprint for the edge installer image.
+
[source,subs="verbatim,quotes"]
--
$ cat rhel9-installer.toml 
name = "rhel9-installer"
description = "blueprint-rhel9-installer"
version = "0.0.1"
--
+
You can also downlod the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/blueprints/rhel9-installer.toml[installer blueprint] from sample applications repository in GitHub.


.. Add a [customizations] installation_device, like for the simplified installer, so I don't need a custom kickstart? It didn't like those customizations. Not even just the install device, without adding users.
+
[source,subs="verbatim,quotes"]
--
ERROR: ManifestCreationFailed: failed to create osbuild manifest: unsupported blueprint customizations found for boot ISO image type "edge-installer": (allowed: User, Group)
--

.. Upload the blueprint to the Image Builder service.
+
[source,subs="verbatim,quotes"]
--
$ composer-cli blueprints push rhel9-installer.toml 
$ composer-cli blueprints list
rhel9-edge
rhel9-installer
--

.. Build an edge installer using the blueprint you just uploaded, referring to the edge commit image that was published in a web server in a xref:ch1-build:s7-ostree-lab.adoc[previous lab].
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose start-ostree rhel9-installer edge-installer --ref rhel/9/x86_64/edge --url http://servera.lab.example.com/repo/
Compose 7a5036e1-4037-4edc-82ff-4c632c0a84fc added to the queue
--

.. Wait until the compose finishes.
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose list
ID                                     Status     Blueprint         Version   Type
7a5036e1-4037-4edc-82ff-4c632c0a84fc   RUNNING    rhel9-installer   0.0.1     edge-installer
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
$ composer-cli compose list
ID                                     Status     Blueprint         Version   Type
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
7a5036e1-4037-4edc-82ff-4c632c0a84fc   FINISHED   rhel9-installer   0.0.1     edge-installer
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
--

.. Download the edge installer image. You should get an ISO file.
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose image 7a5036e1-4037-4edc-82ff-4c632c0a84fc
7a5036e1-4037-4edc-82ff-4c632c0a84fc-installer.iso
--

6. Create a VM that boots from the edge installer image.

.. 1st attempt, it fails to process the kickstart embeded in the ISO. It should *not* display Anaconda screens for choosing packages, installation source, etc.
+
[source,subs="verbatim,quotes"]
--
$ virt-install \
--name edge-test-2 \
--memory 4096 \
--vcpus 2 \
--disk size=40 \
--os-variant rhel9.2 \
--location /home/student/7a5036e1-4037-4edc-82ff-4c632c0a84fc-installer.iso \
--graphics=none \
--extra-arg console=ttyS0 -v
--

.. 2nd attempt, it kinda works, but doesn't work unattended, as it would be expected. It enters anaconda UI stating that the kickstart is unsufficient and asking to enter the "Installation Destination" screen. I enter and accept the defaults of automatic partitioning. Then I can begin installation, it seems to deploy the OSTree commit, and complete the installation. But after rebooting, it stays forever on "A start job is running for…rhel-swap/rhel-root"... just like the previous attempts. :-(
+
Exactly like it did with the previous attempts, using a custom kickstart with the standard RHEL ISO and a remote OSTree repository.
+
[source,subs="verbatim,quotes"]
--
virt-install \
--name edge-test-2 \
--memory 4096 \
--vcpus 2 \
--disk size=40 \
--os-variant rhel9.2 \
--cdrom /home/student/7a5036e1-4037-4edc-82ff-4c632c0a84fc-installer.iso
--

.. I verified the edge installer ISO, it looks good: I can see the osbuild.ks file (with just an ostreesetup command), the grub menus that refer to iso, and the local copy of OSTree repository.

7. Create an edge simplified installer image.
+
This is just to record the test steps, before moving them to their proper place in this course. Previous tests also don't belong here.

.. Need a blueprint which creates an user, else you cannot log in, and that specifies an instllation device (would that be useful for previous attempts?). Unlike other image types, there's no kickstart file to provide such customizations.

+
[source,subs="verbatim,quotes"]
--
name = "rhel9-user"
description = "blueprint-rhel9-user"
version = "0.0.1"

[customizations]
installation_device = "/dev/vda"

[[customizations.user]]
name = "factory"
password = "redhat123"
groups = ["users", "wheel"]
--

.. Upload (and validate???) the blueprint
+
[source,subs="verbatim,quotes"]
--
$ composer-cli blueprints push rhel9-user.toml 
[student@workstation ~]$ composer-cli blueprints list
rhel9-edge
rhel9-installer
rhel9-user
$ composer-cli blueprints depsolve rhel9-user
blueprint: rhel9-user v0.0.1
    acl-2.3.1-3.el9.x86_64
    alternatives-1.20-2.el9.x86_64
...
--

.. Build the simplified installer image, notice it refers to a remote ostree repositor.
+
That makes no sense if my blueprint specifies different packages than that repo -- build first an ostree commit image from the same blueprint? Or use a blueprint without packages and other entries, like for the regular edge installer image? Then, doing a depsolve makes no sense.
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose start-ostree rhel9-user edge-simplified-installer \
--ref rhel/9/x86_64/edge \
--url http://servera.lab.example.com/repo
--

.. Wait until the compose finishes
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose list
ID                                     Status     Blueprint         Version   Type
3024992f-ecb1-4220-9e8b-0816a9480579   RUNNING    rhel9-user        0.0.2     edge-simplified-installer
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
7a5036e1-4037-4edc-82ff-4c632c0a84fc   FINISHED   rhel9-installer   0.0.1     edge-installer
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
--

.. Failed. Why???
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose list
ID                                     Status     Blueprint         Version   Type
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
7a5036e1-4037-4edc-82ff-4c632c0a84fc   FINISHED   rhel9-installer   0.0.1     edge-installer
3024992f-ecb1-4220-9e8b-0816a9480579   FAILED     rhel9-user        0.0.2     edge-simplified-installer
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
--

..  My blueprint specificed a group "users" which didn't exist, my bad, remember to not copy-and-paste without checking. ;-)
+
Among the many expected errors (how would a user know they're expected) there' an unexpected error from `useradd`.
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose log 3024992f-ecb1-4220-9e8b-0816a9480579  | tail
/usr/lib/tmpfiles.d/systemd.conf:25: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:26: Failed to replace specifiers in '/run/log/journal/%m/*.journal*': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:29: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:30: Failed to replace specifiers in '/var/log/journal/%m/system.journal': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:32: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:33: Failed to replace specifiers in '/var/log/journal/%m/system.journal': No such file or directory
Failed to open file "/sys/fs/selinux/checkreqprot": Read-only file system
*useradd: group 'users' does not exist*
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.users", line 188, in <module>
    r = main(args["tree"], args["options"])
  File "/run/osbuild/bin/org.osbuild.users", line 177, in main
    useradd(tree, name, uid, gid, groups, description, home, shell, password)
  File "/run/osbuild/bin/org.osbuild.users", line 105, in useradd
    subprocess.run(["chroot", root, "useradd", *arguments, name], check=True)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['chroot', '/run/osbuild/tree', 'useradd', '--groups', 'users,wheel', '--password', '$6$9jXcx/TeyL5f49.M$7t6GrDWTMWNipVNWLPZxaQecsLlMNYyZMtNJgHH7PoqF0wbfyD37GVXYSbmNoypdgTTo63dVDks0YUPtqeHES0', 'factory']' returned non-zero exit status 6.
--

.. Delete the compose, edit and upload the blueprint, and try again
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose delete 3024992f-ecb1-4220-9e8b-0816a9480579
$ composer-cli compose start-ostree rhel9-user edge-simplified-installer --ref rhel/9/x86_64/edge --url http://servera.lab.example.com/repo
Compose 6da756ac-d8bf-4a58-9152-547f43c7a83b added to the queue
$ composer-cli compose list
ID                                     Status     Blueprint         Version   Type
6da756ac-d8bf-4a58-9152-547f43c7a83b   RUNNING    rhel9-user        0.0.1     edge-simplified-installer
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
7a5036e1-4037-4edc-82ff-4c632c0a84fc   FINISHED   rhel9-installer   0.0.1     edge-installer
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
$ composer-cli compose list
ID                                     Status     Blueprint         Version   Type
01f3796b-85fd-4383-bbe8-eefc9550acdc   FINISHED   rhel9-edge        0.0.1     edge-commit
6da756ac-d8bf-4a58-9152-547f43c7a83b   FINISHED   rhel9-user        0.0.1     edge-simplified-installer
7a5036e1-4037-4edc-82ff-4c632c0a84fc   FINISHED   rhel9-installer   0.0.1     edge-installer
575d8ddc-2902-4de3-a0d5-82f5f194f5d8   FAILED     rhel9-edge        0.0.1     edge-commit
--

.. Download the image from the compose
+
[source,subs="verbatim,quotes"]
--
$ composer-cli compose image 6da756ac-d8bf-4a58-9152-547f43c7a83b
6da756ac-d8bf-4a58-9152-547f43c7a83b-simplified-installer.iso
--

8. Crete a VM that boots from the edge simplified installer image

.. 1st attempt
+
[source,subs="verbatim,quotes"]
--
$ virt-install \
--name edge-test-3 \
--memory 4096 \
--vcpus 2 \
--disk size=40 \
--os-variant rhel9.2 \
--location /home/student/6da756ac-d8bf-4a58-9152-547f43c7a83b-simplified-installer.iso \
--graphics=none \
--extra-arg console=ttyS0 -v
--

.. Got an error :-(
+
[source,subs="verbatim,quotes"]
--
Starting install...
ERROR    Couldn't find kernel for install tree.
Domain installation does not appear to have been successful.
--
+
Google says the previous error was because of --location and I must use --cdrom (so need the ugly VNC console)


.. 2nd attempt
+
[source,subs="verbatim,quotes"]
--
$ virt-install \
--name edge-test-3 \
--memory 4096 \
--vcpus 2 \
--disk size=40 \
--os-variant rhel9.2 \
--boot uefi \
--cdrom /home/student/6da756ac-d8bf-4a58-9152-547f43c7a83b-simplified-installer.iso
--
+
It works well, with UEFI boot.

.. 3rd attempt, seems too hack-ish to me
+
[source,subs="verbatim,quotes"]
--
virt-install --name edge-test-3 --memory 4096 --vcpus 2 --disk size=40 --os-variant rhel9.2 --location /home/student/6da756ac-d8bf-4a58-9152-547f43c7a83b-simplified-installer.iso,kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img --graphics=none --extra-arg console=ttyS0 -v
...
[FAILED] Failed to start Switch Root.
--

.. 4th attempt, uefi does not solve it with --location, only with --cdrom (ignore screen shot of vm console, had a cmd typo). Boot stops with "Failed to start Switch Root.", just like the previous, after adding kernel and initrd to --locaiton. :-(
+
[source,subs="verbatim,quotes"]
--
virt-install \
--name edge-test-4 \
--memory 4096 \
--vcpus 2 \
--disk size=40 \
--os-variant rhel9.2 \
--boot uefi \
--location /home/student/6da756ac-d8bf-4a58-9152-547f43c7a83b-simplified-installer.iso \
--graphics=none \
--extra-arg console=ttyS0 -v
--

Conclusion statement.

== Next Steps

Lorem Ipsum.
