:time_estimate: 16

= Apply, and Rollback Updates to Edge Devices

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Understand how edge devices consume operating system updates from OSTree repositories.

== Device Updates

Edge devices running RHEL for Edge retrieve operating system updates as new system images. They do not download individual package updates from RPM repositories, like package-based RHEL deployments do. You cannot end up in a state where some updates were applied but others weren't. You either update the entire system image or do not update anything.

image::s1-deltas-fig-1.svg[title="End of an edge device installation and update workflow"]

RPM-OSTree keeps two system images side-by-side in a system, and only switches from the current to the new system image with a reboot -- contrast that with RPM package updates, which alter files which may be in use by running processes and may produce unpredictable results.

You can rollback an RPM-OSTree system into a previously known good image -- contrast that with rolling back an update of multiple RPM packages. With package-based systems, you can select an older kernel at boot, but you cannot easily revert all system binaries and dependency libraries, some of which may depend on the kernel version. With an image-based system using RPM-OStree you revert to the the kernel, libraries, and binaries of a previous system image all at once.

You must use the `rpm-ostree` command on an edge device to download (stage) a new system image, and then reboot the system to deploy the new image. The same command allows you to rollback to the previous system image.

In case you download further system updates, the one not currently active is discarded to give room to the new updates, so there are typically just two system images in edge devices and you don't need to prune old updates nor risk exhausting disk space on the devices. It is possible to have three images, for a short period of time, between staging an upgrade and applying that upgrade, during the next reboot, if it was not the first upgrade applied to an edge device.

Both on disk and during download, RPM-OStree takes advantage of OSTree capabilities to not store nor download files that didn't change between the current and the new system image. However, the process of checking file changes can still take multiple network transactions and be slow for systems with low-bandwidth or high-latency network connections. In that case, you're advised to create a static delta on your OSTree repository for faster download of updates.

== Device Updates and Configuration or Application Data

Most of the file system is read-only under RPM-OStree so those contents can be safely replaced during a system update. Only `/etc` and `/var` are read-write, and they are treated in different ways during a system update:

*  Files in `/var` are only touched at first boot, when they're copied from the system image to the writable file system, but updates keep the contents in `/var` unchanged.

* Files in `/etc` are updated with a three-way merge process: the current `/etc` contents are compared with the current system image; differences are applied to a copy of the contents of `/etc` from the new system image; and the result is saved to the writable file system.

The goal is, on one side, to preserve application data in `/var` across system updates, while at the same time enabling applications to include initial data in a system image; and on the other side, to enable new system images to bring new configuration files and change configuration defaults, while preserving local customizations applied to the running system.

If a system update requires changes to application data, for example, migrating data to a new database schema, this is the responsibility of the application. It could run a first boot job to perform the database migration or use any other strategy. Just do not rely on RPM-OSTree itself to make application data compatible with a new version of an application and its dependencies.

== Device Rollbacks and Configuration or Application Data

If you roolback a system update, application data in `/var` is preserved, which might create issues in scenarios such as changes to database schemas required by a new application version: that data could be incompatible with the older version the system is rolling back to. It is the reponsibility of the application to ensure data in `/var` is usable after both updates and rollbacks.

Configuration data in `/etc` is effectively reverted to its old state after a rollback. That happens because each OSTree deployment contains its own `/etc` and files there are merged only at deployment time. The rollback operation just restarts the system to an existing deployment, it will NOT perform a new three-way merge, so any configuration change performed after an update will be lost because of a rollback.

== Building Update Images with Image Builder

An update image is just a regular edge commit image produced by Image Builder, but its single OSTree commit must reference a parent commit so it can be later pulled into a remote OSTree repository and preserve the history if its branch.

image::ch2-publish:s1-ostree-fig-2.svg[title="OSTree repository, branches/references, commits, and remotes"]

If you build an update image without a reference to a parent commit, when you pull it into a remote OSTree repository it will clean all the previous history of its branch. That may cause issues for edge devices that need to rollback to previous images and eliminate the possibility of creating static deltas for updating edge devices on slow networks.

You must start Image Builder composes for updates of edge images with a reference to a remote OSTree repository and a branch. That way, the new edge commit image records the current head of the branch as its parent.

An edge commit image built as an upgrade image, that is, by specifying a reference to a parent commit, is still a complete system image. It contains all files on the image, and the edge commit image contains an OSTree repo with a single commit, without previous history but with metadata about the (missing) parent commit. When it's pulled into a remote OSTree repository, it links to its parent there and the remote repository deduplicates files between the new commit and previous commits already on the repository.

== Distribution of Edge Image Updates

As you develop and test applications, which you embed in an RHEL for Edge system image, you may use multiple OSTree repositories. 

image::s1-deltas-fig-3.svg[title="New edge image, not yet sent to test and production repositories"]

You do not need OSTree and Image Builder for the inner loop: you just test your applications on regular RHEL, before you package them as RPM packages or OCI container images. But, at some moment, you need to perform integration testing using an environment that is as close as possible to your edge devices. You must ensure your image contains the right dependencies and customizations for your applications, so you must build an image and test it, probably using virtual machines.

image::s1-deltas-fig-4.svg[title="New edge image, published on test repositories for integration tests and building edge installer images"]

Assuming your RHEL for Edge system image passes integration tests, you might perform more involved tests, such as performance or functional testing, before you finally declare your system image is clear for production. 

image::s1-deltas-fig-5.svg[title="New edge image, passed all tests and published on production repositories"]

At each of these states, you may use different OSTree repositories, and copy edge images, that is their OSTree commits, from one repository to the next. Finally, you could maintain multiple repositories with copies of the same production images, for fault-tolerance or to serve different geographical regions. This all works because OSTree commit IDs are unique and do not change as you copy them from one repository to another.

What if an edge commit image does not pass tests and is never delivered to production? Just build the next iteration using the same parent OSTree commit as the failed image. That way it replaces the previous iterations on the intermediate OSTree repositories you use for testing, and if it passes all tests it can be added to production repositories.

image::s1-deltas-fig-6.svg[title="New edge image, failed some tests so it's not promoted to production and discarded, and optionally purged from test repositories"]

So, instead of using the latest test image (latest OSTree commit from test repositories) as the parent of the next image you build for testing, you keep using the latest production image (latest successfully delivered to production) as the parent of all test images, until one of them is promoted all the way to production and becomes the new latest. A way of enforcing that is using, during image build, a reference to a production OSTree repository, even if the image being built might never be pulled into the production repository.

You can specify, for an OSTree compose, the URL of a web server which is not the one you intend to use to distribute system images to edge devices in production. That is, your development or testing remote OSTree repository is different than the production repository. An OSTree commit contains no metadata about OSTree remotes. OSTree remotes for fetching upgrades are configured by device-specific customizations, such as Kickstart files, or on day-2.

During testing you usually deploy a test VM (or physical device) as if it's being provisioned for the first time. But, if your testing requires performing an RPM-OSTree update process, to perform tasks such as data schema migration, you can override the OSTree remote on the test machine before applying an update.

IMPORTANT: Edge devices provisioned using edge installer images are *not* configured with a valid OSTree remote. You must configure it before being able to apply any system update.

== Pruning OSTree Repositories

You do not need to prune the local OSTree repository of an edge device because RPM-OStree does that automatically, always keeping at most two deployed system images in the device, plus one optional staged image. Deduplication of OSTree content happens at the file level, not at the branch or commit level, so you can safely prune older commits without losing files that didn't change and are still in use by more recent commits.

Os production or test repositories it may be necessary to implement a process for pruning old commits, based on count, age, or whatever other criteria. Otherwise those repositories may grow unbounded and someday be out of disk space.

OSTree commits are considered derived data: the source of truth of an edge commit image is not the image itself, but the source code used to build its applications, its blueprint, and package list from RPM repositories. It is assumed that you could rebuild an old edge image exactly as it were, by providing the same inputs. So, unlike a source code repository, there is no need to keep historical data on an OSTree repository.

You may need to manually prune an OStree repository of its latest commit. Remember that happens automatically in a test repository, when you pull in a newer test image which uses the same parent as the previous test image. But what if an image was already promoted all the way into production, and only then do you find an issue? Pruning the latest image in a branch of a production repository prevents more edge devices from pulling that image as a system update. For devices that already applied the update, you rollback them to the previous image. And, when you fix whatever issue requires you to remove the latest commit, you provide a fix as a new system image, which is just another image update to all edge devices.

The activities in those courses do not demonstrate pruning OSTree repositories. If you need to perform that, check the `ostree prune` command, in special the options `--delete-commit` and `--keep-younger-than`.

== OSTree Static Deltas

OSTree static delta helps edge devices with challenging network connectivity to download system updates in a more efficient way.

The standard process for downloading OSTree updates is similar to what Rsync, Git, DNF, and similar systems perform, which is basically a file-by-file check. If a system already has the file, move to the next. If it doesn't, download it. This process allows a device to skip updates and move straight to the latest one, instead of having to pass through multiple intermediate updates.

Unfortunately, the standard process requires many network transactions, as a device checks individual files on a remote repository. It does not require lots of bandwidth, as each file check sends very little data over the network but, if anything delays some of the requests or their responses, the overall update may take a long time.

OSTree offers the possibility of pre-computing and storing static deltas between any two commits as part of an OSTree repository. OSTree clients will discover and use these pre-computed deltas, called *static deltas*, transparently, saving network capacity and reducing the time to download updates.

image::s1-deltas-fig-7.svg[title="Edge devices download updates as either static deltas or file-by-file"]

If it happens that an edge device skips an update, for example because it was offline for too long, It will just download changes the usual way, without using the deltas between the current and the previous commit. If you expect this to be a frequent event, you could build static deltas between the current latest and multiple previous commits: one delta for latest → latest-1, another delta for latest → latest-2, one more for latest → latest-3, and so on.

Each static delta takes up disk space on OSTree repository servers, but we usually consider that disk space on servers is cheaper than at edge devices or than network bandwidth to edge devices.

Having static deltas reduces the memory and CPU requirements of servers when updating edge devices. If you consider that an OSTree server has a potentially large population of client-edge devices, compared to the population of developers using a Git repository, the efficiency gains can be large, not to mention a lower cloud bill for running your OSTree servers.

Pre-computed static deltas also save CPU and memory from edge devices while downloading and deploying system updates. The gains are especially welcome by smaller edge devices, which have slower CPUs and less memory than office workstations, and are expected to continue performing their regular tasks while downloading and staging system updates.

In fact, static deltas may be so good for some devices and networks that some RPM-OStree users create empty deltas: they store the difference between a commit and nothing, which is the entire commit. But that empty delta can be queried and downloaded as a single unit, instead of a file-by-file basis, which saves memory, CPU, and network capacity between an edge device and a remote OSTree repository.

== OSTree Summary Files

Every time you update an OSTree repository with multiple branches, updates, and static deltas, you must also update its summary file. Most OSTree clients, such as RPM-OSTree, will check only that summary for information on remote repositories. If that file is outdated, such clients will not be aware of updates or static deltas.

You do not need a summary file for provisioning edge systems or building edge commit images because they either work with a predefined commit or with the latest in a predefined branch. Those processes do not query a remote OSTree repository for the availability of other commits, deltas, or branches.

== Rebasing an Edge Device

It's common to use an OSTree branch to represent a major version of an operating system + applications, and major updates of each become different OSTree branches. This is consistent with the fact that you don't usually phase out major application releases immediately, but keep supporting them with updates and bug fixes for a while. You cannot force all users to switch to a new major release all at once.

A RHEL for Edge system can use the RPM-OStree rebase operation to switch between OSTree branches and thus update to a new operating system or application major release.

Another scenario for performing rebases could be repurposing an existing edge device to run a different application, by switching it to a different branch of the same OSTree repository. It may be worthwhile, compared to reprovisioning devices from scratch, if the branches share the same base operating system and similar dependency libraries.

We are not performing rebases in the hands-on activities, as this is a somewhat rare event -- a major new release frequently requires a hardware refresh. We also do not exercise other RPM-OSTree features, such as applying a mutable layer over `/usr` to install RPM packages outside its system images, but we encourage people to use the `--help` option to explore the verbs of the `rpm-ostree` command and explore its possibilities.

== Next Steps

The final series of hands-on activities in this course builds, installs and rolls back updates to edge system images using test VMs that were provisioned using different methods.
