:time_estimate: 13
:compose-uuid-httpd-v2-aaaaaaaaaaaa: fb5ef664-1def-4589-919d-1a0681f86371

= Lab: Create And Publish Edge Image Updates

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Build RHEL for Edge image updates, publish them as OSTree deltas, and apply the updates to a test VM.

WARNING: Work in Progress

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your development machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a _web server machine_ which serves an OSTree repository. Make sure that machine was configured and verified by following the instructions from xref:ch2-publish:s2-ostree-lab.adoc[a previous lab].

Finally, you need the _test VM_ that you created and published in xref:ch3-test:s2-boot-lab.adoc[another lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. In this case, the `workstation` VM is your _development machine_, and the `servera` VM is your _web server_ machine. If not, please adapt the instructions to your test environment. 

You will perform some steps in this lab on your _development machine_ and some steps on the _web server_ machine. Pay attention to the instructions at each step!

== Instructions

1. On your _development machine_, verify that you have the prerequisites from previous labs.

.. Check that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Check that a remote client can access the OSTree repository in the _web server machine_ and get the current commit ID the OSTree branch with the Apache Web Server system image that you created in xref:ch2-publish:s2-ostree-lab.adoc[a previous lab]. You will get a different ID:
+
[source,subs="verbatim,quotes,attributes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/edge*
{commit-httpd-v1}
--
+
Pay attention to the final path element of the URL, which should be "edge". The commit ID you got will be the parent commit of the edge commit image you are building during this lab.

.. Check that you can manage local VMs, and there's a VM left from the xref:ch3-test:s2-boot-lab:[previous lab] named `edge-test-1`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name          State
---------------------------
 1    edge-test-1   shut-off
 2    edge-db-1     shut-off
--
+
It's fine if the existing VM displays an status of "running" instead of "shut off".

2. On your _developer machine_, make changes to the edge image blueprint to add the Cockpit packages.

.. Open the `rhel9-httpd.toml` file, which you created in a xref:ch1-build:s6-blueprint-lab.adoc[previous lab], with any text editor.
+
Increment the minor version number, in the beginning of the TOML file, add a new `packages` section, and makes changes to its `services` and `firewall` customization sections. The file should look like the following, after all edits:
+
[source,subs="verbatim"]
--
include::1@samples:blueprints:example$rhel9-httpd-v2.toml[]
--
+
You can also download a https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/blueprints/rhel9-httpd-v2.toml[TOML file with all edits] from the course samples repository in GitHub. Beware that the files in the samples repository have different file names, but the same blueprint name, so they can be used as-is, without renaming.

.. Push the updated blueprint to the Image Builder service.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push rhel9-httpd.toml*
--

.. Verify that the blueprint in the Image Builder service contains your changes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints list*
mysql-installer
rhel9-edge
rhel9-mysql
$ *composer-cli blueprints show rhel9-edge*
include::1@samples:blueprints:example$rhel9-httpd-v2.toml[lines=1..3]
...
--

3. Still on your _development machine_, build a new edge commit image from your changed blueprint.
+
This is very similar to what you done in previous labs, but pay attention to the differences required for update images and a few hints about the usage of the `composer-cli` command.

.. Start a compose for an edge commit image and copy its UUID to a shell variable.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose start-ostree rhel9-edge edge-commit --url http://servera.lab.example.com/repo --ref rhel/9/x86_64/edge*
Compose {compose-uuid-httpd-v2-aaaaaaaaaaaa} added to the queue
$ *UUID={compose-uuid-httpd-v2-aaaaaaaaaaaa}*
--
+
IMPORTANT: Be sure you include the URL of your remote OSTree repository and its branch name, so you can use the image from this compose for system updates.

.. Wait until the compose finishes. To avoid clutter from previous labs, this time we filter the list of composes to only show running composes.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list running*
ID                                     Status    Blueprint    Version   Type
{compose-uuid-httpd-v2-aaaaaaaaaaaa}   RUNNING   rhel9-edge   0.2.0     edge-commit
...
$ *composer-cli compose list running*
ID   Status   Blueprint   Version   Type
--

.. Once the list of running composes is empty, it means your compose job either finished or failed. You could filter the list of composes on those statuses, but after some time both lists could become too large for visual inspection. Let's see how to filter the JSON output of `composer-cli` to get the status of just one compose by its UUID:
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose list -j | jq -r ".[1].body.finished[] | select(.id==\"$UUID\").queue_status"*
FINISHED
--

.. If your compose had failed, you would need a different filter, such as:
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose list -j | jq -r ".[2].body.failed[] | select(.id==\"$UUID\").queue_status"*
FAILED
--
+
Because our compose didn't fail, the previous query returns empty.
+
NOTE: You can download, from the source samples repository in GitHub, a https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/sh/status-compose.sh[simple Bash script] that returns the status of a compose gives its UUID. The scrit contains the `jq` from previous commands and also a couple other queries.


.. Download the edge commit image and copy it to your _web sever machine_.
+
Because you have to track two sets of hashes, one for compose UUIDs, another for OSTree commit IDs, use the `--filename` option to give a mnemonic name to the TAR file of your edge commit image. This way, you won't be lost trying to figure out which of your many TAR files corresponds to each edge image, specially after they are moved to a different machine than the one where you run the Image Builder service.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose image $UUID --filename rhel9-httpd-v2-commit.tar*
rhel9-httpd-v2.tar-commit.tar
$ *scp rhel9-httpd-v2-commit.tar servera:~*
...
--

4. Open a terminal on your _web server machine_ and copy the new edge image to the OSTree repository.

.. Check that the new edge commit image exists on your home folder.
+
[source,subs="verbatim,quotes"]
--
$ *ls rhel9-httpd-v2.tar*
rhel9-httpd-v2.tar
--

.. Extract the new edge commit image to an empty temporary directory and verify that it contains a branch that exists on the OSTree repository of the web server.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf rhel9-httpd-v2.tar -C delete-me/*
$ *ostree refs --repo=delete-me/repo*
rhel/9/x86_64/edge
$ *ostree refs --repo=/var/www/html/repo*
rhel/9/x86_64/edge
rhel/9/x86_64/db
--

.. Verify that the OSTree repository contains the commit that your edge commit image references as its parent.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree log rhel/9/x86_64/edge --repo=delete-me/repo*
commit {commit-httpd-v2} <.>
Parent:  {commit-httpd-v1} <.>
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>
$ *ostree log rhel/9/x86_64/edge --repo=/var/www/html/repo*
commit {commit-httpd-v1} <.>
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

--
<.> Commit ID of the new edge commit image
<.> Commit ID of parent of the new edge commit image
<.> Commit ID of the current head of the remote OSTree reposity, which should match the previous commit ID.

.. Now that you verified that your new edge commit image can connect to the existing history of your OSTree repository, pull the new edge commit image into the OSTree repository on the web server.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ostree pull-local --repo=/var/www/html/repo delete-me/repo*
Scanning metadata: 3434
--

.. Update the summary file of the OSTree repository on the web server.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ostree summary -u --repo=/var/www/html/repo*
--

.. As a sanity check, verify that the OSTree repository contains both the new commit, from the new edge commit image, and the previous commit.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree log rhel/9/x86_64/edge --repo=/var/www/html/repo*
commit {commit-httpd-v2} <.>
Parent:  {commit-httpd-v1} <.>
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit {commit-httpd-v1} <.>
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)
--
<.> Commit ID of the new edge commit image
<.> Commit ID of parent of the new edge commit image
<.> Commit ID of the old edge commit image, which is the parent of the new edge commit image

.. You can now delete the temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *rm -rf delete-me*
--

5. Back to your _development machine_, make some changes to configuration and data on your _test VM_, which you created in a xref:ch3-test:s2-boot-lab.adoc[previous lab], so you can verify if those chantes are retained after an update.

.. If your _test VM_ is shut down, start it.
+
[source,subs="verbatim,quotes"]
--
$ *virsh domstate edtge-test-1*
shut off
$ *virsh start edge-test-1*
$ *virsh domstate edtge-test-1*
running
--

.. Attach to the console of your _test VM_ and log in as the user `core` with password `redhat123`. It may be necessary to press kbd:[Enter] a few times to get a login prompt
+
[source,subs="verbatim,quotes"]
--
$ *virsh console edge-test-1*
...
edge login:
--

.. Change the hostname of your _test VM_ and verify that change is stored in a file under the `/etc/` directory.
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ *sudo hostnamectl set-hostname microweb*
[core@edge ~]$ *cat /etc/hostname*
microweb
--
+
You will not see the change of hostname in your shell prompt until you log off.

.. Add a welcome page the Apache Web Server on your _test VM_. Because it is on `/var`, it is treated as application data by RPM-OSTree.
+
Using a text editor, create the `/var/www/html/index.html` with any contents you like, for example:
+
[source,subs="verbatim,quotes"]
--
include::1@samples:html:example$index.html[]
--

.. Check that the Apache Web Server inside your _test VM_ uses your new welcome page.
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ *curl http://127.0.0.1*
include::1@samples:html:example$index.html[lines=1,1]
...
--

6. Again on your _development machine_, stage the new edge commit image on your _test VM_, which you created in a xref:ch3-test:s2-boot-lab.adoc[previous lab].

.. Verify that your _test VM_ is running the system image from the OSTree commit you got at the beginning of this lab.
+
Notice that there's a single OSTree deployment, because your _test VM_ was just provisioned and didn't get any upgrade so far.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: {commit-httpd-v1}
--

.. Verify that your _test VM_ does NOT contain the RPM package which provides Cockpit.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge ~]$ *rpm -q cockpit*
package cockpit is not installed
--

.. Verify that your _test VM_ is preconfigured with an OSTree remote which points to the web server.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge ~]$ *ostree remote list --show-urls*
edge  http://servera.lab.example.com/repo/
--

.. Verify that your _test VM_ can find available upgrades in the remote OSTree repository.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge ~]$ *sudo rpm-ostree upgrade --check*
2 metadata, 0 content objects fetched; 18 KiB transferred in 0 seconds; 0 bytes content written
Note: --check and --preview may be unreliable.  See https://github.com/coreos/rpm-ostree/issues/1579
AvailableUpdate:
        Version: 9.2 (2024-10-09T22:43:27Z)
         Commit: {commit-httpd-v2}
           Diff: 46 added
--
+
NOTE: You safely can ignore the warning about `--check` being unreliable. It refers to the use of `/usr` overlays to install RPMs packages not included in the system image. We are not using this feature of RPM-OSTree.

.. Stage the upgrade on your _test VM_.
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ *sudo rpm-ostree upgrade*
[ 9130.645481] SELinux:  Context system_u:object_r:cockpit_ws_exec_t:s0 is not valid (left unmapped).
[ 9130.658824] SELinux:  Context system_u:object_r:cockpit_session_exec_t:s0 is not valid (left unmapped).
[ 9131.532015] SELinux:  Context system_u:object_r:cockpit_unit_file_t:s0 is not valid (left unmapped).
⠴ Receiving objects; 66% (1605/2400) 58.1 MB/s 116.3 MB                         507 metadata, 1893 content objects fetched; 118645 KiB transferred in 3 seconds; 187.9 MB content written
Receiving objects; 66% (1605/2400) 58.1 MB/s 116.3 MB... done
Staging deployment... done
Added:
  adobe-source-code-pro-fonts-2.030.1.050-12.el9.1.noarch
  cockpit-286.1-1.el9.x86_64
...
Run "systemctl reboot" to start a reboot
--
+
NOTE: You can safely ignore the SELinux errors during staging of a new system image. Those issues are fixed by reboot, when the kernel loads the SELinux policy included in the new system image.

.. You can verify that the new system image is not active (its the second deployment) but it is marked for the next reboot (notice the bullet). 
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge ~]$ *rpm-ostree status*
State: idle
Deployments:
  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-15T20:27:34Z)
                   Commit: {commit-httpd-v1}
                     Diff: 46 added

● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-15T19:56:56Z)
                   Commit: {commit-httpd-v2}
--

7. Still on your _development machine_, apply the upgrade to your _test VM_ and verify it is running the new edge commit image you built during this lab.

.. Reboot your _test VM_, log in again, and verify that the new commit is now the first (active) deployment and also the one marked for the next boot (as indicated by the bullet).
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge ~]$ *sudo systemctl reboot*
...
microweb login:
...
[core@microweb ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T22:43:27Z)
                   Commit: {commit-httpd-v2}

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: {commit-httpd-v1}
--

.. As a sanity check, verify that the OSTree repository on your _test VM_ contains both the new and the previous commits, but nothing more.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *ostree log rhel/9/x86_64/edge*
commit {commit-httpd-v2}
Parent:  {commit-httpd-v1}
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit {commit-httpd-v1}
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)
--

.. To prove it's running the new edge commit image, verify it contains the Cockpit RPM packages:
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *rpm -q cockpit*
cockpit-286.1-1.el9.x86_64
--

.. Check that the changes to configuration and data files were retained by the upgrade.
+
You already noticed the change of hostname in the login and shell prompts of the _test VM_. Now fetch the welcome page of its Apache Web Server.
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ *curl http://127.0.0.1*
include::1@samples:html:example$index.html[]
--

.. If you wish, you can leave the console of your _test VM_ by typing kbd:[Ctrl+\]] and stop your _test VM_. Or you can leave it there to use the terminal for the next activiy and open another terminal on your _development VM_.

You sucessfully built an edge commit image and applied it as an update to a _test VM_, demonstrating that your new system image can upgrade edge devices. You also demonstrated that edge devices retain configuration and application data over system upgrades.

== Next Steps

The next activity builds another edge commit image that is applied as an update and then rolled back, to show how you can revert an RPM-OSTree upgrade of an edge device.