:time_estimate: 12
:compose-uuid-httpd-v3-bbbbbbbbbbbb: fb5ef664-1def-4589-919d-1a0681f86371

= Lab: Rollback Edge Image Updates

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Rollback a test VM to a previous known good RHEL for Edge system image.

WARNING: Work in Progress

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your development machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a _web server machine_ which serves an OSTree repository. Make sure that machine was configured and verified by following the instructions from xref:ch2-publish:s2-ostree-lab.adoc[a previous lab].

Finally, you need the _test VM_ that you updated in xref:s2-update-lab.adoc[the previous lab]. While you could perform the focus tasks in this lab on a _test VM_ that was never updated before, that is, you can rollback the first update of an edge device, the instructions and outputs here assume that there are previous updates already applied to the _test VM_, to demonstrate that RPM-OSTree automatically prunes older system updates.

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. In this case, the `workstation` VM is your _development machine_, and the `servera` VM is your _web server_ machine. If not, please adapt the instructions to your test environment. 

You will perform some steps in this lab on your _development machine_ and some steps on the _web server_ machine. Pay attention to the instructions at each step!

== Instructions

1. On your _development machine_, verify that you have the prerequisites from previous labs.

.. Check that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Check that you can get the current commit ID the OSTree branch with the Apache Web Server system image update that you created in xref:s2-update-lab.adoc[the previous lab]. You will get a different ID:
+
[source,subs="verbatim,quotes,attributes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/edge*
{commit-httpd-v2}
--
+
Pay attention to the final path element of the URL, which should be "edge". The commit ID you get should be the active commit in your _test VM_ and it will be the parent commit of the new update image you are building during this lab.

.. Check that you can manage local VMs, and there's a VM left from the xref:s2-update-lab:[previous lab] named `edge-test-1`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name          State
---------------------------
 1    edge-test-1   shut-off
 2    edge-db-1     shut-off
--
+
It's fine if the existing VM displays an status of "running" instead of "shut off".

2. Make changes to the edge image blueprint to add the PHP packages.
+
This similar to what you did in the previous lab. It's just another update image, which should pick whatever is the current HEAD of the remote OSTree repository as its parent.

.. Open the `rhel9-httpd.toml` file which you edited in the xref:s2-update-lab.adoc[previous lab], with any text editor.

.. Increment the version number, in tbe beginning of the TOML file, and add two `packages` sections, one for the PHP interpreter and another for the PHP-FastCGI engine. There is no need to change any of the `customizations` section. After your edits, the TOML file should look like the following:
+
[source,subs="verbatim"]
--
include::1@samples:blueprints:example$rhel9-httpd-v3.toml[lines=1..18]

...
--
+
You can also download a https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/blueprints/rhel9-httpd-v3.toml[TOML file with all edits] from the course samples repository in GitHub. Beware that the file in the samples repository have different file names, but the same blueprint name, so they can be used as-is, without renaming.


.. Push the updated blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli push blueprints rhel9-httpd.toml*
--

.. Verify that the blueprint in the Image Builder service contains your changes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints list*
mysql-installer
rhel9-edge
rhel9-mysql
$ *composer-cli blueprints show rhel9-edge*
include::1@samples:blueprints:example$rhel9-httpd-v3.toml[lines=1..3]
...
--

3. Still on your _development machine_, build another new edge commit image from your changed blueprint.
+
This is similar to what you did in the previous lab. You just need something different from the previous images so you later can verify that your _test VM_ got the right updates.

.. Start a compose for an edge commit image and copy its UUID to a shell variable.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose start-ostree rhel9-edge edge-commit --url http://servera.lab.example.com/repo --ref rhel/9/x86_64/edge*
Compose {compose-uuid-httpd-v3-bbbbbbbbbbbb} added to the queue
$ *UUID={compose-uuid-httpd-v3-bbbbbbbbbbbb}*
--

.. Wait until the compose finishes.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list running*
ID                                     Status    Blueprint    Version   Type
{compose-uuid-httpd-v3-bbbbbbbbbbbb}   RUNNING   rhel9-edge   0.3.0     edge-commit
...
$ *composer-cli compose list running*
ID   Status   Blueprint   Version   Type
--

.. Make sure your compose finished sucessfully. Pay attention to the compose UUID and version so you don't check the status of the wrong compose. 
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list finished*
ID                                     Status     Blueprint     Version   Type
...
{compose-uuid-httpd-v3-bbbbbbbbbbbb}   FINISHED   rhel9-edge    0.3.0     edge-commit
...
--
+
NOTE: You can alternatively use a https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/sh/status-compose.sh[simple Bash script] that returns the status of a compose given its UUID.


.. Download the edge commit image and copy it to your _web sever machine_.
+
Be careful to not overwrite the TAR files of previous edge commit images, because you might need them to reconstruct your remote OSTree repository in case you make mistakes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose image $UUID --filename rhel9-httpd-v3-commit.tar*
rhel9-httpd-v3-commit.tar
$ *scp rhel9-httpd-v3-commit.tar servera:~*
...
--

4. On your _web server machine_, copy the new edge image to the OSTree repository.

.. Extract your new edge commit image into an empty temporary directory and check that its parent commit exists on the OSTree repository of the _web server_ machine.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ls rhel9-httpd-v3-commit.tar*
rhel9-httpd-v3-commit.tar
$ *mkdir delete-me*
$ *tar xf rhel9-httpd-v3-commit.tar -C delete-me/*
$ *ostree log rhel/9/x86_64/edge --repo=delete-me/repo*
commit {commit-httpd-v3} <.>
Parent:  {commit-httpd-v2} <.>
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
2024-10-17 15:11:55 +000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>
$ *ostree log rhel/9/x86_64/edge --repo=/var/www/html/repo*
commit {commit-httpd-v2} <.>
Parent:  {commit-httpd-v1}
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit {commit-httpd-v1}
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

--
<.> Commit ID of the new edge commit image
<.> Parent commit of the new edge image
<.> Current Head of the OSTree repository, should match the parent commit.

.. Pull your new edge commit image from the temporary directory into your OSTree repository and update its summary file. You can now delete the temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ostree pull-local --repo=/var/www/html/repo delete-me/repo*
36 metadata, 65 content objects imported; 0 bytes content written 
$ *sudo ostree summary -u --repo=/var/www/html/repo*
$ *rm -rf delete-me*
--

.. Verify that the OSTree repo now contains the commit ID from your new edge container image as its HEAD and still contains all previous commit IDs.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree log rhel/9/x86_64/edge --repo=/var/www/html/repo*
commit {commit-httpd-v3} <.>
Parent:  {commit-httpd-v2} <.>
ContentChecksum:  645322fc333084d0613ebfc43f8dbe8c1fe1ae19c9e176270dd2bc7688c6145a
Date:  2024-10-17 15:11:55 +0000
Version: 9.2
(no subject)

commit {commit-httpd-v2} <.>
Parent:  {commit-httpd-v1} <.>
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit {commit-httpd-v1} <.>
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

--
<.> Commit ID of the new edge commit image
<.> Parent commit of the new edge commit image
<.> Previous commit, it was the HEAD at the beginning of this lab
<.> Parent commmit of the previous commit, it was the initial commit
<.> Initial commit

5. Still on your _development machine_, stage the new edge commit image on your _test VM_.

.. If your _test VM_ is shut down, start it. Then and connect to its console and log in as the user `core` with password `redhat123`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh domstate edge-test-1*
shut off
$ *virsh start edge-test-1*
$ *virsh domstate edge-test-1*
running
$ *virsh console edge-test-1*
...
microweb login:
--

.. Verify that your _test VM_ is running the system image from the OSTree commit ID you got at the beginning of this lab. Notice that there are two OSTree deployments, because your _test VM_ was already updated in the previous lab.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: {commit-httpd-v2}
  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: {commit-httpd-v1}
--

.. Verify that your _test VM_ does not contain any PHP packages.
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *rpm -q php*
package php is not installed
--

.. Verify that your _test VM_ finds another update available in the remote OSTree repository. The commit ID of the update should match the commit ID of your new edge commit image.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *sudo rpm-ostree upgrade --check*
2 metadata, 0 content objects fetched; 18 KiB transferred in 0 seconds; 0 bytes content written
Note: --check and --preview may be unreliable.  See https://github.com/coreos/rpm-ostree/issues/1579
AvailableUpdate:
        Version: 9.2 (2024-10-17T15:11:55Z)
         Commit: {commit-httpd-v3}
           Diff: 2 added
--

.. Stage the upgrade on your _test VM_.
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *sudo rpm-ostree upgrade*
⠤ Scanning metadata: 2691                                                       37 metadata, 65 content objects fetched; 14453 KiB transferred in 4 seconds; 57.6 MB content written
Scanning metadata: 2691... done
Staging deployment... done
Added:
  nginx-filesystem-1:1.20.1-14.el9.noarch
  php-8.0.27-1.el9_1.x86_64
  php-common-8.0.27-1.el9_1.x86_64
  php-fpm-8.0.27-1.el9_1.x86_64
Run "systemctl reboot" to start a reboot
--

6. Still on your _development machine_, apply the upgrade to your _test VM_ and verify it is running the new edge commit image you built during this lab.

.. Reboot your _test VM_ and verify that the older commit was discarded by RPM-OSTree, so the local repository of the edge device stays with only two commits.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *sudo systemctl reboot*
...
microweb login:
...
[core@microweb ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-17T15:11:55Z)
                   Commit: {commit-httpd-v3}

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-15T20:27:34Z)
                   Commit: {commit-httpd-v1}
--

.. To prove it's running the new edge commit image, verify it contains the PHP packages:
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *rpm -q php*
php-8.0.27-1.el9_1.x86_64
--

7. Still on your _development machine_, change configurations and application data on your _test VM_, so you can verify if those changes are retained by rolling back an update.

.. Change the timezone of your _test VM_.
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *date*
Thu Oct 17 21:45:58 UTC 2024
[core@microweb ~]$ *sudo timedatectl set-timezone America/Aruba*
[core@microweb ~]$ *date*
Thu Oct 17 17:46:53 AST 2024
--

.. Using a text editor, create the `/var/www/html/info.php` script with the following contents;
+
[source,subs="verbatim,quotes"]
--
include::1@samples:html:example$info.php[]
--

.. Check that the Apache Web Server inside your _test VM_ runs your PHP script.
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *curl http://127.0.0.1/info.php*
<html>
<body>
This is PHP version: 8.0.27</body>
</html>
--

8. Still on your _developer machine_, suppose that you discovered the new edge commit image contains a serious security issue and you must rollback your _test VM_ to the previous system image, to verify that the bad update can be rolled back.

.. Rollback your _test VM_.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *sudo rpm-ostree rollback*
Moving '{commit-httpd-v2}.0' to be first deployment
Transaction complete; bootconfig swap: no; bootversion: boot.0.0, deployment count change: 0
Removed:
  nginx-filesystem-1:1.20.1-14.el9.noarch
  php-8.0.27-1.el9_1.x86_64
  php-common-8.0.27-1.el9_1.x86_64
  php-fpm-8.0.27-1.el9_1.x86_64
Changes queued for next boot. Run "systemctl reboot" to start a reboot
--

.. Check that now the old commit is marked as the one for the next boot (notice the bullet on the second deployment) but the current commit was NOT discarded by rolling back from it.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *rpm-ostree status*
State: idle
Deployments:
  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-15T20:27:34Z)
                   Commit: {commit-httpd-v3}
                     Diff: 2 removed

  ● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-17T15:11:55Z)
                   Commit: {commit-httpd-v2}
--

.. After reboot (and login) both commits are still in the system, but they switch order. Notice that the second deployment is the newer commit, which was the bad update, and is now inactive.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@microweb ~]$ *sudo systemctl reboot*
...
microweb login:
...
[core@microweb ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-15T20:27:34Z)
                   Commit: {commit-httpd-v2}

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-17T15:11:55Z)
                   Commit: {commit-httpd-v3}
--

.. Verify that the _test VM_ does NOT contain PHP packages anymore, but still contains the Cockpit packages, so it is indeed running the update from the previous lab.
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *rpm -q php*
package php is not installed
[core@microweb ~]$ *rpm -q cockpit*
cockpit-286.1-1.el9.x86_64
--

.. Check that your _test VM_ still contains the changes to timezone and the PHP script, which doesn't work anymore because there's no PHP engine on its Apache Web Server.
+
[source,subs="verbatim,quotes"]
--
[core@microweb ~]$ *date*
Thu Oct 17 22:45:04 UTC 2024
[core@microweb ~]$ *timedatectl show -p Timezone*
Timezone=Etc/UTC
[core@microweb ~]$ *curl http://127.0.0.1/info.php*
include::1@samples:html:example$info.php[]
--

As you see, rolling back an RPM-OSTree system just switches the active system image for the next boot. The newer but inactive system image remains available in edge devices, and could me marked active again, until a future upgrade removes it.

Also notice that a system rollback does NOT rollbacks changes to configuration and application data. If your upgrade required special handling of application data, your rollback will also require it.

== Next Steps

The next and final lab of this course applies updates to a VM that was provisioned using an edge installer image and demonstrates the use of static deltas for faster staging of updates.
