:time_estimate: 11

= Lab: Update Edge Devices Using Static Deltas

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Update a test VM, that was provisioned using an edge installer image, using OSTree deltas.

WARNING: Work in Progress

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is member of the `weldr` group. Make sure your development machine was configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a _web server machine_ which serves an OSTree repository. Make sure that machine was configured and verified by following the instructions from xref:ch2-publish:s2-ostree-lab.adoc[a previous lab].

Finally, you need the _test VM_ that you created and published in xref:ch2-publish:s2-boot-lab.adoc[another lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on and newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. In this case, the `workstation` VM is your _development machine_, and the `servera` VM is your _web server_ machine. If not, please adapt the instructions to your test environment. 

[ REVIEW NEXT PARA ]

You will some steps in this lab on your _development machine_ and some steps on the _web server_ machine.

[ Make one lab perform an update without a delta, and the other with a delta? ]

[ Add commands to start VMs and connect to their consoles ]

== Instructions

1. On your _development machine_, verify that you have the prerequisites from previous labs.

.. Verify that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-76-2.el9_2.x86_64
...
--

.. Check that a remote client can access the OSTree repository in the web server machine.
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/config*
[core]
repo_version=1
mode=archive-z2
--

.. Check that you can get the current commit ID the OSTree branch with the httpd edge system image that you created in xref:ch2-publish:s3-ostree-lab.adoc[a previous lab]. Your will get a different ID:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/edge*
4afeda6a96ec8b2c263b6965a9c3f92db1db2436ae1e1233da70b7776fc6137b
--
+
Pay attention to the final path element of the URL, which should be "edge".

.. Check that you can manage local VMs, and there's a VM left from the xref:s2-boot-lab:[previous lab] named `edge-test-1`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name          State
---------------------------
 1    edge-test-1   shut-off
 2    edge-db-1     shut-off
---
+
It's fine the existing VM displays an status of "running" instead of "shut off".

2. Make changes to the edge image blueprint to add a custom welcome page to the Apache Web Server.

.. Open the `rhel9-httpd.toml` file which you created in a xref:ch1-build-blueprint-lab.adoc[previous lab], with any text editor.

.. Increment the version number, in tbe beginning of the TOML file, and add a `customizations.file` section with an inline HTML page, to the end of the TOML file.
+
[ didn't work, switch to adding the cockpit package ]
+
[source,subs="verbatim,quotes"]
--
name = "rhel9-edge"
description = "blueprint-rhel9-edge"
version = "0.0.2"
...
[[customizations.files]]
path = "/var/www/html/index.html"
mode = "0644"
user = "root"
group = "root"
data = """
<html>
<body>
<h1>I am an Edge Device!</h1>
</body>
</html>
"""--

.. Push the updated blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli push blueprints rhde-build-samples/blueprints/rhel9-httpd-v2.toml*
--

.. Verify that the blueprint in the Image Builder service contains your changes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints list*
mysql-installer
rhel9-edge
rhel9-mysql
$ *composer-cli blueprints show rhel9-edge*
name = "rhel9-edge"
description = "blueprint-rhel9-edge"
version = "0.0.2"
...
--

3. Still on your _development machine_, build an edge commit image from your changed blueprint.

.. Start a compose for an edge commit image and copy its UUID to a shell variable.
+
[ do I need a parent? looks like I have to reference the external repo ]
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose start-ostree rhel9-edge edge-commit --url http://servera.lab.example.com/repo --ref rhel/9/x86_64/edge*
Compose fb5ef664-1def-4589-919d-1a0681f86371 added to the queue
$ *UUID=fb5ef664-1def-4589-919d-1a0681f86371*
--

.. Wait until the compose finishes. To avoid clutter from previous labs, this time we filter the list of composes.
+
[ try a better filter with jq. why can't I ask just the status of a given compose? :-() ]
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose list running*
ID                                     Status    Blueprint    Version   Type
fb5ef664-1def-4589-919d-1a0681f86371   RUNNING   rhel9-edge   0.0.2     edge-commit
$ *composer-cli compose list running*
ID   Status   Blueprint   Version   Type
$ *composer-cli compose list finished*
ID                                     Status     Blueprint     Version   Type
...
fb5ef664-1def-4589-919d-1a0681f86371   FINISHED   rhel9-edge    0.0.2     edge-commit
--

.. Download the edge commit image and copy it to your _web sever machine_.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose image $UUID*
fb5ef664-1def-4589-919d-1a0681f86371-commit.tar
$ *scp $UUID-commit.tar servera:~*
...
--

4. On your _web server machine_, copy the new edge image to the OSTree repository.

.. Copy the shell variable with the UUID of the new edge commit image and check that it exists on your home folder.
+
[source,subs="verbatim,quotes"]
--
$ *UUID=fb5ef664-1def-4589-919d-1a0681f86371*
$ *ls $UUID-commit.tar*
fb5ef664-1def-4589-919d-1a0681f86371-commit.tar
--

.. Extract the edge commit image and pull it into the OSTree repository.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf $UUID-commit.tar -C delete-me/*
$ *sudo ostree pull-local --repo=/var/www/html/repo delete-me/repo*
506 metadata, 1893 content objects imported; 0 bytes content written
--

.. Verify that the OSTree repo contains the same branch than your new edge commit image. The OSTree repo should contain additional branches.
+
[source,subs="verbatim,quotes"]
--
$ *ostree refs --repo=delete-me/repo*
rhel/9/x86_64/edge
$ *ostree refs --repo=/var/www/html/repo*
rhel/9/x86_64/edge
rhel/9/x86_64/db
--

.. Verify that the OSTree repo contains the same commit than your new edge commit image.
+
[ looks like my pull overwrote everything in the branch with the new commit and discarded the old one :-( ]
+
[ do I fix this at build time or at pull time? looks like at build time ]
+
[ parent must be 4afeda6a96ec8b2c263b6965a9c3f92db1db2436ae1e1233da70b7776fc6137b for consistency with previous labs ]
+
[source,subs="verbatim,quotes"]
--
$ *ostree log rhel/9/x86_64/edge --repo=delete-me/repo*
commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>
$ *ostree log rhel/9/x86_64/edge --repo=/var/www/html/repo*
commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

--

5. Now how do I get and apply the update to the test VM?


+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$  rpm-ostree status
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
[core@edge ~]$ sudo rpm-ostree upgrade --check
2 metadata, 0 content objects fetched; 18 KiB transferred in 0 seconds; 0 bytes content written
Note: --check and --preview may be unreliable.  See https://github.com/coreos/rpm-ostree/issues/1579
AvailableUpdate:
        Version: 9.2 (2024-10-09T22:43:27Z)
         Commit: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
           Diff: 46 added
[core@edge ~]$ sudo rpm-ostree upgrade
[ 9130.645481] SELinux:  Context system_u:object_r:cockpit_ws_exec_t:s0 is not valid (left unmapped).
[ 9130.658824] SELinux:  Context system_u:object_r:cockpit_session_exec_t:s0 is not valid (left unmapped).
[ 9131.532015] SELinux:  Context system_u:object_r:cockpit_unit_file_t:s0 is not valid (left unmapped).
⠴ Receiving objects; 66% (1605/2400) 58.1 MB/s 116.3 MB                         507 metadata, 1893 content objects fetched; 118645 KiB transferred in 3 seconds; 187.9 MB content written
Receiving objects; 66% (1605/2400) 58.1 MB/s 116.3 MB... done
Staging deployment... done
Added:
  adobe-source-code-pro-fonts-2.030.1.050-12.el9.1.noarch
  cockpit-286.1-1.el9.x86_64
...
Run "systemctl reboot" to start a reboot
$ systemctl reboot
...
boot messages
...
new login
...
[core@edge ~]$ rpm-ostree status
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T22:43:27Z)
                   Commit: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746

[core@edge ~]$ ostree log rhel/9/x86_64/edge
commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

[core@edge ~]$ rpm -q cockpit
cockpit-286.1-1.el9.x86_64
--
+
Notice the bullet on rpm-ostree status to show which is the active deployment
+
[ do static detlas now or later? ]
+
[ I didn't do "ostreee summary -u"  what is its purpose? ]

.. Info om remotes depends on summary files on server
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ ostree remote refs edge
error: Remote refs not available; server has no summary file

after [student@servera ~]$ sudo ostree summary -u --repo=/var/www/html/repo

[core@edge ~]$ ostree remote refs edge
edge:rhel/9/x86_64/edge
--


6. Build another update and pull to the ostree repo

.. Have three commits in the branch.
+
[ any way of setting the subject during a pull local? or at image build time? ]
+
[source,subs="verbatim,quotes"]
--
[student@servera ~]$ ostree refs --repo /var/www/html/repo
rhel/9/x86_64/edge
[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo /var/www/html/repo
commit cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  a366c9c7b9887f26356db475c62aee3197ccdb505fe90406b391b11b049e47d0
Date:  2024-10-10 16:37:33 +0000
Version: 9.2
(no subject)

commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)
--

.. Have two commits deployed
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ rpm-ostree status
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T22:43:27Z)
                   Commit: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T20:25:03Z)
                   Commit: 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
--

.. VM sees no updates available, try again after updating the summary, it works.
+
[ I cannot see how the issue linked makes --check unreliable. guess it's just about layered packages, not about image/commit updates ]
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ sudo rpm-ostree upgrade --check
2 metadata, 0 content objects fetched; 18 KiB transferred in 0 seconds; 0 bytes content written
Note: --check and --preview may be unreliable.  See https://github.com/coreos/rpm-ostree/issues/1579
AvailableUpdate:
        Version: 9.2 (2024-10-10T16:37:33Z)
         Commit: cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
           Diff: 2 added
[core@edge ~]$ sudo rpm-ostree upgrade 
⠠ Scanning metadata: 2370                                                       37 metadata, 65 content objects fetched; 14453 KiB transferred in 3 seconds; 57.6 MB content written
Scanning metadata: 2370... done
Staging deployment... done
Added:
  php-8.0.27-1.el9_1.x86_64
  php-common-8.0.27-1.el9_1.x86_64
Run "systemctl reboot" to start a reboot
--

.. After reboot, see that the commit from initial deployment of the VM was discarded.
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ rpm-ostree status
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-10T16:37:33Z)
                   Commit: cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T22:43:27Z)
                   Commit: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
[core@edge ~]$ rpm -q cockpit
cockpit-286.1-1.el9.x86_64
[core@edge ~]$ rpm -q php
php-8.0.27-1.el9_1.x86_64--


7. Rollback to the previous image, which didn't have php, but only cockpit

.. Rollback and reboot
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ sudo rpm-ostree rollback
[sudo] password for core: 
Moving '4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b.0' to be first deployment
Transaction complete; bootconfig swap: no; bootversion: boot.0.0, deployment count change: 0
Removed:
  php-8.0.27-1.el9_1.x86_64
  php-common-8.0.27-1.el9_1.x86_64
Changes queued for next boot. Run "systemctl reboot" to start a reboot
[core@edge ~]$ sudo systemctl reboot
...
--

.. After reboot (and relogin) both commits are still in the system, but they switch order
+
[source,subs="verbatim,quotes"]
--
[core@edge ~]$ rpm-ostree status
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-09T22:43:27Z)
                   Commit: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b

  edge:rhel/9/x86_64/edge
                  Version: 9.2 (2024-10-10T16:37:33Z)
                   Commit: cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88

[core@edge ~]$ rpm -q cockpit
cockpit-286.1-1.el9.x86_64
[core@edge ~]$ rpm -q php
package php is not installed
--


[ keeping commit hashes consistent between labs will be a pain. maye it's time to use asciidoc attributes? ]

[ with the edge-db VM, you need to configure a remote before applying updates ]

[ there's rpm-ostree update, to get a newer commit of the same branch, and rpm-ostree rebase, to switch to a different branch which uses a different RHEL release ]


[ to make a lab using the edge-db VM more interesting (instead of 90%+ the same as this) could configure automatic image updates
But then we'd miss automatic rollbacks (greenboot) which I didn't put in scope here, this course is already too long
 https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/composing_installing_and_managing_rhel_for_edge_images/index#proc_upgrading-your-rhel-8-system-to-rhel-9_managing-rhel-for-edge-images ]

[ After an update, grub shows two entries (new and old deployment) show it here or in the next lab with the db VM? ]

[ should I start with an empty remote ostree repo and reference it since the first build? The way it is now, the first build is different than other builds. ]

[ Use --filename to not have to deal with UUIDs? ]

[ changed the "y" version to see if image builder preserves them, and increments only the "z" number when you push a bp that overwrites an existing one ]

////
begin Jq to filter composes

$ composer-cli compose list -j | jq ".[1].body.finished[] | select(.id==\"$UUID\")"
{
  "blueprint": "rhel9-edge",
  "compose_type": "edge-commit",
  "id": "e03d42c5-d60a-4ce2-8f4f-e4c5c2b34201",
  "image_size": 0,
  "job_created": 1728577818.9874678,
  "job_finished": 1728578265.801976,
  "job_started": 1728577818.9923553,
  "queue_status": "FINISHED",
  "version": "0.0.2"
}
$ composer-cli compose list -j | jq ".[1].body.finished[] | select(.id==\"$UUID\").queue_status"
"FINISHED"
$ composer-cli compose list -j | jq ".[1].body.finished[] | select(.id==\"$UUID\") | [.blueprint, .queue_status]"
[
  "rhel9-edge",
  "FINISHED"
]
$ composer-cli compose list -j | jq ".[1].body.finished[] | select(.id==\"$UUID\") | .blueprint + \": \" + .queue_status"
"rhel9-edge: FINISHED"

# not tested yet, but should work for running composes

$ composer-cli compose list -j | jq ".[0].body.run[] | select(.id==\"$UUID\").queue_status"

end
////

////
begin prune commits

started with three commits in the branch

[student@servera ~]$ ostree refs --repo /var/www/html/repo
rhel/9/x86_64/edge
[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo /var/www/html/repo
commit cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  a366c9c7b9887f26356db475c62aee3197ccdb505fe90406b391b11b049e47d0
Date:  2024-10-10 16:37:33 +0000
Version: 9.2
(no subject)

commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

commit 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

Deleted the commit in the middle

$ sudo ostree prune --delete-commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b --repo /var/www/html/repo
[sudo] password for student: 
Total objects: 31172
Deleted 22 objects, 13.9 MB freed

Lost history! :-(

[student@servera ~]$ sudo ostree log rhel/9/x86_64/edge --repo /var/www/html/repo
commit cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  a366c9c7b9887f26356db475c62aee3197ccdb505fe90406b391b11b049e47d0
Date:  2024-10-10 16:37:33 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>


So I should use the prune --delete-commit command to remove the head of branch, like to remve a bad updatre and preventing more devices from getting it.

end
////


////
begin static deltas

Starting with three commits in the branch

At first. no deltas in my repo

[student@servera ~]$ ostree static-delta list --repo /var/www/html/repo
(No static deltas)

[student@servera ~]$ sudo ostree static-delta generate rhel/9/x86_64/edge --repo /var/www/html/repo
Generating static delta:
  From: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
  To:   cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
modified: 13
new reachable: metadata=36 content regular=53 symlink=12
rollsum for 0/13 modified
processing bsdiff: [0/11]
processing bsdiff: [1/11]
processing bsdiff: [2/11]
processing bsdiff: [3/11]
processing bsdiff: [4/11]
processing bsdiff: [5/11]
processing bsdiff: [6/11]
processing bsdiff: [7/11]
processing bsdiff: [8/11]
processing bsdiff: [9/11]
processing bsdiff: [10/11]
Killed

Was the 'killed' message expected or a sign of trouble? My disk is almost full.

ostree fsck says I'm still good and ostree static-delta list returns empty

scp the entire repo to workstation and doing the commands there

[student@workstation ~]$ ostree static-delta generate rhel/9/x86_64/edge --repo ostree/repo/
Generating static delta:
  From: 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
  To:   cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
modified: 13
new reachable: metadata=36 content regular=53 symlink=12
rollsum for 0/13 modified
processing bsdiff: [0/11]
processing bsdiff: [1/11]
processing bsdiff: [2/11]
processing bsdiff: [3/11]
processing bsdiff: [4/11]
processing bsdiff: [5/11]
processing bsdiff: [6/11]
processing bsdiff: [7/11]
processing bsdiff: [8/11]
processing bsdiff: [9/11]
processing bsdiff: [10/11]
fallback for 02b2a4244f8b3db7248bf784237ca39b9304527ded8ee9033621b1354e069807 (6.8 MB)
part 1 n:46 compressed:696045 uncompressed:49739412
part 2 n:53 compressed:301665 uncompressed:1198953
uncompressed=50938365 compressed=997710 loose=560538
rollsum=0 objects, 0 bytes
bsdiff=11 objects

Hey, the "killed" might be because of the kernel OOM Killer, in that case I need more memory on servera.
Confirmed, dmesg shows the OOM messages

[16655.203087] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-3.scope,task=ostree,pid=2270,uid=0
[16655.204792] Out of memory: Killed process 2270 (ostree) total-vm:737900kB, anon-rss:458868kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1004kB oom_score_adj:0

servera is less than 1G RAM.

[student@servera ~]$ free -h
               total        used        free      shared  buff/cache   available
Mem:           771Mi       394Mi        57Mi       6.0Mi       449Mi       376Mi
Swap:             0B          0B          0B
[student@servera ~]$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda4       9.4G  5.6G  3.8G  61% /
[student@servera ~]$ sudo dd if=/dev/zero of=/swap bs=1M count=1024
[sudo] password for student: 
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.20099 s, 256 MB/s
[student@servera ~]$ du -sh /swap 
1.0G    /swap
[student@servera ~]$ sudo mkswap /swap
mkswap: /swap: insecure permissions 0644, fix with: chmod 0600 /swap
Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
no label, UUID=1ca66288-c317-41ee-9287-22708ab54c8e
[student@servera ~]$ sudo chmod 0600 /swap 
[student@servera ~]$ sudo swapon /swap
[student@servera ~]$ free -h
               total        used        free      shared  buff/cache   available
Mem:           771Mi       378Mi        56Mi       6.0Mi       468Mi       392Mi
Swap:          1.0Gi          0B       1.0Gi

Let's see if my 1G swap was enough to prevent OOM

In the meantime, trying an empty delta on workstation

[student@workstation ~]$ ostree summary -u --repo ostree/repo/
[student@workstation ~]$ ostree static-delta list  --repo ostree/repo/
4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b-cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88

the "empty" delta generates many more messages (because there's more stuff packed on it)

[student@workstation ~]$ ostree static-delta generate --empty rhel/9/x86_64/edge --repo ostree/repo/
Generating static delta:
  From: empty
  To:   cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
modified: 0
new reachable: metadata=3503 content regular=24335 symlink=2985
rollsum for 0/0 modified
fallback for d1a50732d88ad80ef541ad6f51b5858abd10425622257529e8f67eee7e0e9569 (13.4 MB)
fallback for 5316cea99d220bf7c7401d030d5522ffd6c6bb6cbc0bd94864081adc68e30925 (29.1 MB)
fallback for 7411ad0abd796b98e28da0652bba68a284b0339923278af3fe1a2ef1f42a9136 (11.3 MB)
fallback for b926924c33ea2a5b9b679281d89fdfc4a8828605409bf3ab99d3db2bdd1e60ec (4.4 MB)
fallback for c985dded9ffb627058eeedd8a173c5c47c39b7469210181f2ca189f0344b8a32 (15.0 MB)
fallback for 02b2a4244f8b3db7248bf784237ca39b9304527ded8ee9033621b1354e069807 (6.8 MB)
fallback for b7cb81d1f257845b2cfe470e850048efe190372abbc02611b67a248de377c87f (17.5 MB)
fallback for 083d2224f3999a45b88f26dbc1f2fe93de85e0c0b01d6b672017196ea6e8aab8 (9.0 MB)
fallback for ab607714c1858adfcbce6ce1040d1a0f4dae861453d3da0e51fa38b5ba2ff8d9 (15.4 MB)
fallback for a11ae6310d49791caeea4baf98d8a57b752850f1ff99fb3276d14a31ba240bc2 (26.8 MB)
fallback for 7e493333ebe56a6eca986b674654ab3c271013541aa7df75b239e8d80360f092 (4.5 MB)
fallback for 0816eb2ea4d2a1d5ef5f266a8f4249029af5afc497b9bfa20584830f5c28448a (10.0 MB)
fallback for be09d97710d15310edf40a797f9e9cfca85a22cd78ccc6d1756e9e1ae3acf92f (6.7 MB)
fallback for 5593647774d9e1b8cdd5b882688d88927b7e93dc51dc801eb18912ef06994c84 (8.5 MB)
fallback for 899e29a5faa340f0ca2a5a232bec478a30eb9c82896a53d9bec7597778b5710e (88.2 MB)
fallback for 04b9cebea5b708a4fc9075db37a19066384cb8f9e03bbd9c80bfa5f04a056432 (12.2 MB)
fallback for aa043ae804cf44e8c07cf8f9efe0fa15cbe267e8140e70b17e6ec8118a418fac (4.1 MB)
fallback for 1ee5a7d922241e5afe69ff55d12e919b1c0435305a9de1d1cac88678eaf0c354 (5.9 MB)
fallback for 06f22a14a93b98a8cfe82bf0eb6d4b4ac7189ca40f8e5a545810e3304ed0433c (4.4 MB)
fallback for ea1f035d97d3c5a7a32d45fac21f245d95030a8d7ee038158c1296a141e318e4 (10.1 MB)
fallback for 043ccca292f6c1dba0b536fe58412f8f585b76c9dcbd0304cc4d7a56ae5080bd (5.2 MB)
fallback for 9d66c7bb676b62c1affbc3b085f2dddaeefde1f7b80187d13c7d1a524862b1b4 (5.9 MB)
fallback for 65574f925e42fd731a028923177853a0728a1a6ab2d14fe7f8a1edbf772c5540 (44.3 MB)
fallback for 096ed81a1f7cde93e513f37c66fffb68c7083dabb4e8e6389d94d6dcf472a1eb (49.3 MB)
fallback for cd02a062e4886c73488a5cf6499de18b24d33cbae6f26264f01dcf4d852a52bc (12.9 MB)
fallback for c33780dae41ea260ce69d71f835940e12409a5719dfbd6bc4ea2d395956b28dc (28.4 MB)
fallback for e9dc4a9a20f238620e8dc7f25a409c5c0a3b0b28b5e0b74eb2c97af19283cbd6 (13.4 MB)
fallback for c9eefd0ae5115084612fb9f088cd6b39832bb334805b87dc5e9dfc8e84bee2d6 (4.7 MB)
part 1 n:4202 compressed:17654629 uncompressed:31990891
part 2 n:1161 compressed:18360841 uncompressed:31996811
part 3 n:1015 compressed:15346541 uncompressed:31615570
part 4 n:1044 compressed:18307597 uncompressed:30993008
part 5 n:782 compressed:19239617 uncompressed:31049600
part 6 n:972 compressed:21069445 uncompressed:31657993
part 7 n:796 compressed:16585221 uncompressed:30196643
part 8 n:777 compressed:19034217 uncompressed:31991665
part 9 n:823 compressed:16713593 uncompressed:31983829
part 10 n:973 compressed:16725301 uncompressed:31975039
part 11 n:925 compressed:18152637 uncompressed:30256452
part 12 n:1036 compressed:15324461 uncompressed:31864765
part 13 n:717 compressed:16260937 uncompressed:31093667
part 14 n:867 compressed:17973417 uncompressed:29149437
part 15 n:894 compressed:20794105 uncompressed:31945963
part 16 n:774 compressed:20183625 uncompressed:31925387
part 17 n:830 compressed:19614421 uncompressed:31965231
part 18 n:814 compressed:18673181 uncompressed:31668281
part 19 n:865 compressed:17585705 uncompressed:30596735
part 20 n:889 compressed:16899273 uncompressed:30864879
part 21 n:909 compressed:15913005 uncompressed:31959207
part 22 n:729 compressed:17482269 uncompressed:30805152
part 23 n:807 compressed:15890525 uncompressed:31915953
part 24 n:715 compressed:15487277 uncompressed:31416158
part 25 n:649 compressed:16381785 uncompressed:31930191
part 26 n:785 compressed:16790849 uncompressed:31961515
part 27 n:896 compressed:18922693 uncompressed:31891189
part 28 n:1080 compressed:16684673 uncompressed:31660603
part 29 n:3068 compressed:2458729 uncompressed:5464234
uncompressed=885786048 compressed=496510569 loose=553126637
rollsum=0 objects, 0 bytes
bsdiff=0 objects

[student@workstation ~]$ ostree static-delta list  --repo ostree/repo/
4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b-cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88

end
////

////
begin add metadata to a commit, cannot be done with image builder, would add new commits to the repo

the checkout and commit trick requires sudo (just publishing could do without) and I have to check that I can install/boot from the results. Also, checkout and commit are slow :-(

# first

[student@servera ~]$ ostree refs --repo v1/repo
rhel/9/x86_64/edge
[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo v1/repo
commit 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

[student@servera ~]$ rm -rf delete-me/
[student@servera ~]$ sudo ostree checkout 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746 delete-me --repo v1/repo
[student@servera ~]$ sudo ostree commit --parent 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746 --subject 'web server v1' delete-me --branch rhel/9/x86_64/edge --repo v1/repo
71c8addf9c11707070c7f565cdff1682d4fc0849439d924d57762a63028833b0

[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo v1/repo
commit 71c8addf9c11707070c7f565cdff1682d4fc0849439d924d57762a63028833b0
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-10 21:38:43 +0000

    web server v1

commit 7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  f938c449602ad38c31a74bd35f0e438beb833e8ca592c07c87ef90a56f659586
Date:  2024-10-09 20:25:03 +0000
Version: 9.2
(no subject)

crap messed up, commit to the wrong repo, must start over :-(

# second

[student@servera ~]$ sudo rm -rf delete-me

[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo v2/repo
commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>
[student@servera ~]$ sudo ostree checkout 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b delete-me --repo v2/repo

[student@servera ~]$ sudo ostree commit --parent 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b --subject 'web server v2' delete-me --branch rhel/9/x86_64/edge --repo v2/repo
3f10da18855512fb69920fd14133dff1a5ef8683298a387ee18d127bbec2797b

[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo v2/repo
commit 3f10da18855512fb69920fd14133dff1a5ef8683298a387ee18d127bbec2797b
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-10 22:19:16 +0000

    web server v2

commit 4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
Parent:  7ff678881e89e96c90eb083b905dce411740caf19c524481d7c1b848647b5746
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-09 22:43:27 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>

# third

[student@servera ~]$ sudo rm -rf delete-me

[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo v3/repo
commit cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  a366c9c7b9887f26356db475c62aee3197ccdb505fe90406b391b11b049e47d0
Date:  2024-10-10 16:37:33 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>

[student@servera ~]$ sudo ostree checkout cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88 delete-me --repo v3/repo

[student@servera ~]$ sudo ostree commit --parent cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88 --subject 'web server v3' delete-me --branch rhel/9/x86_64/edge --repo v3/repo
c324e0e2573aa3231d6a4be93f4ea34d5abc09d134fa51d5ae9bd0ab84ccbc4b

[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo v3/repo
commit c324e0e2573aa3231d6a4be93f4ea34d5abc09d134fa51d5ae9bd0ab84ccbc4b
Parent:  cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
ContentChecksum:  a366c9c7b9887f26356db475c62aee3197ccdb505fe90406b391b11b049e47d0
Date:  2024-10-10 22:24:30 +0000

    web server v3

commit cfd48bbd633b68844c4ca8122f26e5fa36d8aad929525c61331d0aab5c3d3e88
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  a366c9c7b9887f26356db475c62aee3197ccdb505fe90406b391b11b049e47d0
Date:  2024-10-10 16:37:33 +0000
Version: 9.2
(no subject)

<< History beyond this commit not fetched >>

# looks like it installs when the repo contains only #first

[student@servera ~]$ sudo ostree pull-local --repo=/var/www/html/repo v2/repo
506 metadata, 1893 content objects imported; 0 bytes content written                                                                                                 
[student@servera ~]$ 
[student@servera ~]$ 
[student@servera ~]$ ostree log rhel/9/x86_64/edge --repo /var/www/html/repo
commit 3f10da18855512fb69920fd14133dff1a5ef8683298a387ee18d127bbec2797b
Parent:  4caef3752842366bbeab77b57b79854c6cb7bf4f2b62e82190cfba5d1cc3c12b
ContentChecksum:  94e275f4f9c9a9f68426ed9421845a48065467aea8bfcb57d826ed43fa50a253
Date:  2024-10-10 22:19:16 +0000

    web server v2

<< History beyond this commit not fetched >>

# crap, pull-local of #second deleted the history. :-(

# next attempt: creating the original state (three commits in the repo) and ammend only head.d

# other attempt: building the update images from the commit that got metadata. add summary to repo (not image!), get id, build v2, add metadata, upgrade device

end
////


////
begin

Need more updates to show:

1. That an edge device only keeps the latest two updates (or how to prune older from devices)
2. That I can retire an update, after finding it failed in many devices, so other devices won't get it
3. That retiring an update (removing a commit from an ostree repo) won't break the chain from head to previous, and I can still rollback to those olders if I find more issues or regressions -- OK if a device already rolled back, it has no previous to go. I must push whatever they need to go back to as if it's a newer one.

end
////