:time_estimate: 14
:compose-uuid-mysql-v2-bbbbbbbbbbbb: e0722e00-9cd1-4d7f-96fc-83776eac85fc

= Lab: Update Edge Devices Using Static Deltas

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Update a test VM, that was provisioned using an edge installer image, using OSTree static deltas.

== Before you Begin

You need a _development machine_ with RHEL and configured with the Image Builder service, its CLI and web UI, and a user that is a member of the `weldr` group. Make sure your development machine is configured and verified by following the instructions from the xref:ch1-build:s4-install-lab.adoc[first lab].

You also need a _web server machine_ which serves an OSTree repository. Make sure that the machine was configured and verified by following the instructions from xref:ch2-publish:s2-ostree-lab.adoc[a previous lab].

Finally, you need the _database VM_ that you created in xref:ch3-test:s3-installer-lab.adoc[another lab].

These instructions were tested on RHEL 9.5 but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions to the `servera` VM from the same user. In this case, the `workstation` VM is your _development machine_, and the `servera` VM is your _web server machine_. If not, please adapt the instructions to your test environment. 

You will perform some steps of this lab on your _development machine_ and some steps on your _web server machine_. Pay attention to the instructions at each step, when they request that you switch to a different machine!

== Instructions

////
it seems "user" doesn't work well with ostree (at least installer images) but a %post-install script does ]
https://bugzilla.redhat.com/show_bug.cgi?id=1838859

Got confirmation that the edge installer image ships with a different Anaconda setup which doesn't enable all options. While the RHEL installer is optimized for interactive installation, the edge installer is optmised for unattended installation.
https://redhat-internal.slack.com/archives/C022TDCV3FH/p1729527320272209?thread_ts=1729268869.980959&cid=C022TDCV3FH

They claim users from blueprints should work and have root access (wheel group)  but that failed in my tests
UPDATE: users in blueprints are deprecated, at least for ostree images.
////

1. On your _development machine_, verify that you have the prerequisites from previous labs.

.. Check that the Image Builder service is active and that the current Linux user can submit requests to it.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli status show*
API server status:
    Database version:   0
    Database supported: true
    Schema version:     0
    API version:        1
    Backend:            osbuild-composer
    Build:              NEVRA:osbuild-composer-118-1.el9.x86_64
...
--

.. Check that you can get the current commit ID of the OSTree branch with the database edge system image that you created in xref:ch2-publish:s3-pull-local-lab.adoc[a previous lab]. You will get a different ID.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *curl http://servera.lab.example.com/repo/refs/heads/rhel/9/x86_64/db*
{commit-mysql-v1}
--
+
Pay attention to the final path element of the URL, which should be "db".

.. Check that you can manage local VMs, and that there's a VM left from a xref:ch3-test:s3-installer-lab:[previous lab] named `edge-db-1`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name          State
---------------------------
 1    edge-test-1   shut-off
 2    edge-db-1     shut-off
--
+
It's fine the existing VM displays a status of "running" instead of "shut off".

2. Make changes to the edge image blueprint to add the Nano text editor.

.. Open the `rhel9-mysql.toml` file which you created in a xref:ch2-publish:s3-pull-local-lab.adoc[previous lab], with any text editor.

.. Increment the version number, at the beginning of the TOML file, and add a `packages` section that refers to packages from Nano text editor.
+
[source,subs="verbatim,quotes"]
--
include::1@samples:blueprints:example$rhel9-mysql-v2.toml[]
--
+
You can also download a https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/blueprints/rhel9-mysql-v2.toml[TOML file with all edits] from the course samples repository in GitHub. Beware that the files in the samples repository have different file names, but the same blueprint name, so they can be used as-is, without renaming.

.. Push the updated blueprint.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints push rhel9-mysql.toml*
--

.. Verify that the blueprint in the Image Builder service contains your changes.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli blueprints list*
mysql-installer
rhel9-edge
rhel9-mysql
$ *composer-cli blueprints show rhel9-mysql*
include::1@samples:blueprints:example$rhel9-mysql-v2.toml[lines=1..3]
...
--

3. Build an edge commit image from your changed blueprint.

.. Start a compose for an edge commit image and copy its UUID to a shell variable.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose start-ostree rhel9-mysql edge-commit --url http://servera.lab.example.com/repo --ref rhel/9/x86_64/db*
Compose {compose-uuid-mysql-v2-bbbbbbbbbbbb} added to the queue
$ *UUID={compose-uuid-mysql-v2-bbbbbbbbbbbb}*
--
IMPORTANT: Ensure that the branch name of the previous command ends with "db". You don't want to build this image as an update to the web server image from previous labs!

.. Wait until the compose finishes.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *composer-cli compose list running*
ID                                     Status    Blueprint    Version   Type
{compose-uuid-mysql-v2-bbbbbbbbbbbb}   RUNNING   rhel9-db     0.2.0     edge-commit
...
$ *composer-cli compose list running*
ID   Status   Blueprint   Version   Type
$ *composer-cli compose list finished*
ID                                     Status     Blueprint     Version   Type
...
{compose-uuid-mysql-v2-bbbbbbbbbbbb}   FINISHED   rhel9-db      0.2.0     edge-commit
...
--

.. Download the edge commit image and copy it to your _web server machine_.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose image $UUID --filename rhel9-mysql-v2-commit.tar*
rhel9-mysql-v2-commit.tar
$ *scp rhel9-mysql-v2-commit.tar servera:~*
...
--

4. On your _web server machine_, copy the new edge image to the OSTree repository.

.. Extract your new edge commit image and check that the OSTree repo contains the "db" branch and that your new edge commit image contains the same branch.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir delete-me*
$ *tar xf rhel9-mysql-v2-commit.tar -C delete-me/*
$ *ostree refs --repo=delete-me/repo*
rhel/9/x86_64/db
$ *ostree refs --repo=/var/www/html/repo*
rhel/9/x86_64/edge
rhel/9/x86_64/db
--

.. Check that your new edge commit image connects to the latest commit of the "db" branch.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree log rhel/9/x86_64/db --repo=delete-me/repo*
commit {commit-mysql-v2}
Parent:  {commit-mysql-v1}
ContentChecksum:  4b48cd779032b8b360f7b7bcb79e5148fd47a110ebc0946007fd5b4045ba0da5
Date:  2024-10-21 23:02:11 +0000
Version: 9.5
(no subject)

<< History beyond this commit not fetched >>
$ *ostree log rhel/9/x86_64/db --repo=/var/www/html/repo*
commit {commit-mysql-v1}
ContentChecksum:  6a4989dab6c787b5c4acc161569154cefe6928829af914bc092d65e3234489cb
Date:  2024-10-18 15:36:53 +0000
Version: 9.5
(no subject)(no subject)

--

.. Copy the new edge commit image to the remote OSTree repository and update its summary file. You can now delete the temporary directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ostree pull-local --repo=/var/www/html/repo delete-me/repo*
93 metadata, 105 content objects imported; 0 bytes content writte
$ *sudo ostree summary -u --repo=/var/www/html/repo*
$ *rm -rf delete-me*
--

.. Verify that the remote OSTree repository now contains the new commit, from your new edge commit image.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree log rhel/9/x86_64/db --repo=/var/www/html/repo*
commit {commit-mysql-v2}
Parent:  {commit-mysql-v1}
ContentChecksum:  4b48cd779032b8b360f7b7bcb79e5148fd47a110ebc0946007fd5b4045ba0da5
Date:  2024-10-21 23:02:11 +0000
Version: 9.5
(no subject)

commit {commit-mysql-v1}
ContentChecksum:  6a4989dab6c787b5c4acc161569154cefe6928829af914bc092d65e3234489cb
Date:  2024-10-18 15:36:53 +0000
Version: 9.5
(no subject)

--

5. Create a static delta on the remote OSTree repository.

.. Check that there are no static deltas in the remote OSTree repository.
+
[source,subs="verbatim,quotes"]
--
$ *ostree static-delta list --repo /var/www/html/repo*
(No static deltas)
--

.. Create a static delta between the current database image and the previous one.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *sudo ostree static-delta generate rhel/9/x86_64/db --repo /var/www/html/repo*
Generating static delta:
  From: {commit-mysql-v1}
  To:   {commit-mysql-v2}
modified: 11
new reachable: metadata=93 content regular=103 symlink=2
rollsum for 0/11 modified
processing bsdiff: [0/11]
...
part 1 n:103 compressed:379009 uncompressed:48900526
part 2 n:94 compressed:588953 uncompressed:2660939
uncompressed=51561465 compressed=967962 loose=1340818
rollsum=0 objects, 0 bytes
bsdiff=11 objects
--

.. Remember to update the summary file, every time you change the remote OSTree repository.
+
[source,subs="verbatim,quotes"]
--
$ *ostree summary -u --repo /var/www/html/repo*
--

.. Check that now the remote OSTree repository contains a static delta.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *ostree static-delta list --repo /var/www/html/repo*
{commit-mysql-v1}-{commit-mysql-v2}
--

6. Back to your _development machine_, stage the upgrade on the _database VM_.

.. If your _database VM_ is shut down, start it. Then connect to its console and log in as the user `core` with password `redhat123`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh domstate edge-db-1*
shut off
$ *virsh start edge-db-1*
$ *virsh domstate edge-db-1*
running
$ *virsh console edge-db-1*
...
edge-db login:
--

.. Check that your _database VM_ is running the system image from the OSTree commit ID you got at the beginning of this lab.
+
There should be a single deployment, that is, a single OSTree commit and system image on the local OSTree repository, because the _database VM_ wasn't updated yet.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge-db ~]$ *rpm-ostree status*
State: idle
Deployments:
● edge:rhel/9/x86_64/edge
                  Version: 9.5 (2024-10-09T20:25:03Z)
                   Commit: {commit-mysql-v1}
--

.. Check that your _database VM_ contains MySQL packages but no Nano packages.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *rpm -q mysql*
mysql-8.0.36-1.el9_3.x86_64
[core@edge-db ~]$ *rpm -q nano*
package nano is not installed
--

.. Check that, because this VM was provisioned using an edge installer image, it is NOT configured with a valid OSTree remote.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *ostree remote list --show-urls*
db  file:///run/install/repo/ostree/repo
--

.. Configure your _database VM_ with an OSTree remote that points to your _web server_ machine.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *sudo ostree remote delete db*
[core@edge-db ~]$ *sudo ostree remote add --no-gpg-verify db http://servera.lab.example.com/repo*
[core@edge-db ~]$ *ostree remote list --show-urls*
db  http://servera.lab.example.com/repo
--

.. Check that your _database VM_ can find available updates on the remote OSTree repository.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge-db ~]$ *sudo rpm-ostree upgrade --check*
2 metadata, 0 content objects fetched; 18 KiB transferred in 0 seconds; 0 bytes content written
Note: --check and --preview may be unreliable.  See https://github.com/coreos/rpm-ostree/issues/1579
AvailableUpdate:
        Version: 9.5 (2024-10-21T23:02:11Z)
         Commit: {commit-mysql-v2}
           Diff: 1 added
--

.. Stage the upgrade and reboot the _database VM_ to apply its updates. Then check it's running the new system image, which contains the Nano text editor.
+
[source,subs="verbatim,quotes,attributes"]
--
[core@edge-db ~]$ *sudo rpm-ostree upgrade*
...
Staging deployment... done
Added:
  nano-5.6.1-6.el9.x86_64
Run "systemctl reboot" to start a reboot
$ *sudo systemctl reboot*
...
edge-db login:
...
[core@edge-db ~]$ *rpm-ostree status*
State: idle
Deployments:
● db:rhel/9/x86_64/db
                  Version: 9.2 (2024-10-21T23:02:11Z)
                   Commit: {commit-mysql-v2}

  db:rhel/9/x86_64/db
                  Version: 9.2 (2024-10-18T15:36:53Z)
                   Commit: {commit-mysql-v1}
[core@edge-db ~]$ *rpm -q nano*
nano-5.6.1-6.el9.x86_64
--
+

7. Verify that your _database VM_ actually fetched upgrades using static deltas.

.. Search the system logs on the _database VM_. You should see two entries with a message `libostree pull`: one from checking for updates, which refers to no deltas and has a small transfer size, and another from the actual upgrade operation, which refers to a delta and with a larger transfer size.
+
[source,subs="verbatim,quotes"]
--
[core@edge-db ~]$ *sudo journalctl --no-pager -t rpm-ostree -g pull*
Oct 22 15:39:53 db rpm-ostree[1246]: libostree pull from 'db' for rhel/9/x86_64/db complete
                                     security: GPG: disabled 
                                     security: SIGN: disabled http: TLS
                                     non-delta: meta: 2 content: 0
                                     transfer: secs: 0 size: 18.5 kB
Oct 22 15:40:45 db rpm-ostree[1246]: libostree pull from 'db' for rhel/9/x86_64/db complete
                                     security: GPG: disabled 
                                     security: SIGN: disabled http: TLS
                                     delta: parts: 2 loose: 2
                                     transfer: secs: 3 size: 993.2 kB
-- Boot c7ab9e1e55944e17a38672c152c9106d --
--
+
NOTE: If you do not see any evidence of using static deltas to perform the upgrade operation, it might be because you forgot to update the summary file of the remote OSTree repository after creating the static delta. In that case, the upgrade didn't use the available static delta.

.. If you search the system log of the _test VM_ from the previous labs, you will see entries similar to the following.
+
[source,subs="verbatim,quotes"]
--
Oct 22 16:39:47 edge rpm-ostree[1232]: libostree pull from 'edge' for rhel/9/x86_64/edge complete
                                       security: GPG: disabled 
                                       security: SIGN: disabled http: TLS
                                       non-delta: meta: 2 content: 0
                                       transfer: secs: 0 size: 18.5 kB
Oct 22 16:40:00 edge rpm-ostree[1232]: libostree pull from 'edge' for rhel/9/x86_64/edge complete
                                       security: GPG: disabled 
                                       security: SIGN: disabled http: TLS
                                       non-delta: meta: 507 content: 1893
                                       transfer: secs: 7 size: 121.5 MB
-- Boot dc233afb346f4aa2b9e25d64ae9f4c3c --
--
+
Notice that all entries are `non-delta` pulls.

7. Switch to your _web server machine_ and verify that the web server served requests for using static deltas.

.. Check the last lines of the access logs of the Apache Web Server. They should include requests with a path of `/repo/deltas` which refer to the two parts of the delta as seen on the logs from the `rpm-ostree` command in the previous step.
+
[source,subs="verbatim,quotes"]
--
$ *sudo tail /var/log/httpd/access_log*
172.25.250.9 - - [22/Oct/2024:15:43:42 -0400] "GET /repo/objects/74/85f70a7dbf8379b53c11548af162032260689e517eccded498d112c59460a3.commitmeta HTTP/1.1" 404 196 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:15:43:42 -0400] "GET /repo/objects/74/85f70a7dbf8379b53c11548af162032260689e517eccded498d112c59460a3.commit HTTP/1.1" 200 18260 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/summary.sig HTTP/1.1" 404 196 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/summary HTTP/1.1" 200 672 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/config HTTP/1.1" 200 58 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/delta-indexes/dI/X3Cn2_g3m1PBFUivFiAyJgaJ5Rfsze1JjREsWUYKM.index HTTP/1.1" 200 205 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/deltas/NJ/F_p7mLUGVaFohIhIZAg08t_5AOM_B9alxYSLKRm44-dIX3Cn2_g3m1PBFUivFiAyJgaJ5Rfsze1JjREsWUYKM/superblock HTTP/1.1" 200 25012 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/deltas/NJ/ F_p7mLUGVaFohIhIZAg08t_5AOM_B9alxYSLKRm44-dIX3Cn2_g3m1PBFUivFiAyJgaJ5Rfsze1JjREsWUYKM/0 HTTP/1.1" 200 379009 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:15:44:29 -0400] "GET /repo/deltas/NJ/F_p7mLUGVaFohIhIZAg08t_5AOM_B9alxYSLKRm44-dIX3Cn2_g3m1PBFUivFiAyJgaJ5Rfsze1JjREsWUYKM/1 HTTP/1.1" 200 588953 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:16:02:35 -0400] "HEAD /repo HTTP/1.1" 301 - "-" "curl/7.76.1"
--
<.> Request for the summary file, from which an edge device finds about the availability of static deltas.
<.> Request for the indexes of deltas, from which an edge device finds if there's a delta that matches its upgrade operations
<.> Request for the superblock of the desired delta, from which an edge device finds its parts
<.> Request for part 1 of the delta 
<.> Request for part 2 of the delta

.. If you were checking the logs from upgrading the _test VM_ from the previous lab, you would see requests similar to the following.
+
[source,subs="verbatim,quotes"]
--
...
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/summary HTTP/1.1" 200 672 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/config HTTP/1.1" 200 58 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/delta-indexes/k1/Buyn565biiarvRuIyecbXDRoMYVrzR5IcYoZFo68w.index HTTP/1.1" 404 196 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/93/506eca7e7ae5b8a26abbd1b88c9e71b5c346831856bcd1e48718a19168ebcc.commitmeta HTTP/1.1" 404 196 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/eb/049ca6ed02d59965726ea3820798c6295f72643447e40e1e70405bcee57fad.dirtree HTTP/1.1" 200 1095 "-" "libostree/2022.6" <.>
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/0c/838feff043ef5f56180b54e340733174765fb47c51341edc6937cb5b724970.dirtree HTTP/1.1" 200 815 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/56/76902fc461f868f4e2f1b214a21b582b9c941a6dfd9fcbc114d234d65c14dd.dirtree HTTP/1.1" 200 34351 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/7e/a2c5410038e1f58baeddddee3b775e64c304296f574c872f5f92e8623df2d0.dirtree HTTP/1.1" 200 9675 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/a6/5d2dc8c573696c941646077906a4984ef9ab485d565170e45940508dc96812.dirtree HTTP/1.1" 200 2699 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/a6/35c3efc51056fe97f5674427f12574b9e9ed925959afc64b1634713df02abb.dirtree HTTP/1.1" 200 32916 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/6a/66c95127808bb8c723e163b7a0557a54f010132deb04b70a15bd15d0269f74.dirtree HTTP/1.1" 200 4454 "-" "libostree/2022.6"
172.25.250.9 - - [22/Oct/2024:16:39:52 -0400] "GET /repo/objects/13/5479584d3d98616cedfb7c334995cb819177b7c13966e7386bb39b72b2e863.dirtree HTTP/1.1" 200 19012 "-" "libostree/2022.6"
...
--
<.> Request for the summary file, from which an edge device finds about the availability of static deltas.
<.> Request for the indexes of deltas, notice it fails with HTTP error 404 because there are no deltas for the commit on the _test VM_.
<.> Request for the commit metadata, from which an edge device gets a list of files on the OSTree commit.
<.> From now on, many requests, possibly hundreds or thousands, one for each individual file and directory in the OSTree commit.

As you see, the usage of static deltas is transparent to administrators of edge devices. Upgrades will not fail because there are no static deltas, and you wouldn't notice any performance improvement if your updates are small as in the examples of this course and network connectivity between edge devices end their remote OSTree repositories is good.

== Next Steps

This was the last activity in this course. Stay tuned for the remaining Red Hat Device Edge courses, which feature MicroShift, Ansible Automation, Green Boot, and FDO.