= Summary

In this chapter, you learned:

* No matter how you provision your edge devices, they need access to remote OSTree repositories to fetch system updates.

* Edge commit images used for system updates must be created with a reference to an existing OSTree repository and an OSTree branch with at least one commit.

* Devices provisioned using edge installer images are *NOT* configured with an OSTree remote, you must configure it before applying updates.

* RPM-OSTree stages upgrades on the system disk, as a new OSTree commit, and applies then on the next boot. It also keeps the previous OSTree commit so you can rollback from the upgrade.

* Changes to files in `/etc` and `/var` are retained during system updates and rollbacks.

* OSTree static deltas between two OSTree commits make system upgrades faster and more reliable for devices with high latency or low-bandwidth network connections, and most be created manually.

* Every time you add commits or static deltas to an OSTree repository, you must update its summary file.
